#!/usr/bin/env node
/**
 * Tailwind cannot apply an opacity modifier to a colour held in a CSS variable:
 * `bg-[var(--bg-primary)]/60` produces no CSS, so such inputs and panels fell
 * back to the browser's white. This script finds every such class in the source
 * and writes equivalent `color-mix()` rules to `app/alpha.css`.
 *
 *   node scripts/gen-alpha.mjs          write app/alpha.css
 *   node scripts/gen-alpha.mjs --check  fail when app/alpha.css is stale
 */
import { readFileSync, readdirSync, statSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const out = join(root, 'app', 'alpha.css');

const PROP = {
  bg: ['background-color'],
  text: ['color'],
  fill: ['fill'],
  stroke: ['stroke'],
  outline: ['outline-color'],
  ring: ['--tw-ring-color'],
  decoration: ['text-decoration-color'],
  caret: ['caret-color'],
  accent: ['accent-color'],
};
const BORDER_SIDES = { '': ['border-color'], '-t': ['border-top-color'], '-b': ['border-bottom-color'], '-l': ['border-left-color'], '-r': ['border-right-color'], '-x': ['border-left-color', 'border-right-color'], '-y': ['border-top-color', 'border-bottom-color'] };
const VARIANT = { hover: ':hover', focus: ':focus', 'focus-within': ':focus-within', active: ':active', disabled: ':disabled', open: '[open]' };

const files = [];
const walk = (dir) => {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (['node_modules', '.next', 'out', 'scripts'].includes(name)) continue;
    if (statSync(p).isDirectory()) walk(p);
    else if (/\.(tsx?|jsx?)$/.test(name)) files.push(p);
  }
};
for (const dir of ['app', 'components', 'hooks', 'lib']) if (existsSync(join(root, dir))) walk(join(root, dir));

const re = /(?<![\w:-])((?:[a-z-]+:)*)(bg|border(?:-[trblxy])?|text|ring|outline|fill|stroke|decoration|caret|accent)-\[var\((--[\w-]+)\)\]\/(\d{1,3})(?![\w])/g;
const rules = new Map();
for (const file of files) {
  const text = readFileSync(file, 'utf8');
  for (const m of text.matchAll(re)) {
    const [cls, variants, prefix, variable, alpha] = m;
    const props = prefix.startsWith('border') ? BORDER_SIDES[prefix.slice(6)] : PROP[prefix];
    if (!props) continue;
    const suffix = variants
      .split(':')
      .filter(Boolean)
      .map((v) => VARIANT[v])
      .join('');
    if (variants.split(':').filter(Boolean).some((v) => !(v in VARIANT))) continue; // responsive/group variants are not generated
    const selector = `.${cls.replace(/[^\w-]/g, (c) => `\\${c}`)}${suffix}`;
    const value = `color-mix(in srgb, var(${variable}) ${alpha}%, transparent)`;
    rules.set(selector, props.map((p) => `${p}: ${value};`).join(' '));
  }
}

// base rules first, then the state variants, so a variant always wins
const ordered = [...rules.entries()].sort((a, b) => Number(/[:[]/.test(a[0].replace(/\\./g, ''))) - Number(/[:[]/.test(b[0].replace(/\\./g, ''))) || a[0].localeCompare(b[0]));
const css =
  '/* Generated by scripts/gen-alpha.mjs — do not edit. Opacity modifiers on CSS-variable colours. */\n' +
  ordered.map(([selector, body]) => `${selector} { ${body} }`).join('\n') +
  '\n';

if (process.argv.includes('--check')) {
  const current = existsSync(out) ? readFileSync(out, 'utf8') : '';
  if (current !== css) {
    console.error('[alpha] app/alpha.css is out of date — run `npm run gen:alpha -w @otto/web`');
    process.exit(1);
  }
  console.log(`[alpha] ok — ${rules.size} rules`);
} else {
  writeFileSync(out, css);
  console.log(`[alpha] wrote ${rules.size} rules to app/alpha.css`);
}
