import type { HelpText } from './types';

const text: HelpText = {
  title: 'Sənədlər',
  subtitle: 'zeithub.otto — süni intellektlə lokal proqramlaşdırma studiyasıdır: çat, alətli agent, redaktor, tapşırıqlar, servislər və modellər bir pəncərədə.',
  searchPlaceholder: 'Sənədlərdə axtar…',
  contents: 'Mündəricat',
  nothing: 'Heç nə tapılmadı. Başqa söz sınayın.',
  inMain: 'Əsas pəncərədə açılır',
  overview: 'İcmal',
  prev: 'Əvvəlki',
  next: 'Sonrakı',
  openWindow: 'Ayrıca pəncərədə aç',
  quick: [
    { n: '1', title: 'Model qoşun', text: 'Lokal Ollama («Modellər» tabı) və ya Parametrlərdə pulsuz bulud açarı.', view: 'models' },
    { n: '2', title: 'Layihə açın', text: '«Yeni layihə» → qovluq seçin. Layihə kliklə açılır, çatlar onun içindədir.', view: 'chat' },
    { n: '3', title: 'Tapşırıq verin', text: 'Çatda nə edəcəyini yazın. Agent faylları oxuyur, kod yazır və səhifəni brauzerdə yoxlayır.', view: 'chat' },
  ],
  sections: [
    {
      id: 'start', title: 'Sürətli başlanğıc',
      lead: 'Quraşdırmadan ilk nəticəyə qədər üç addım.',
      items: [
        '**Model.** Lokal: «Modellər» tabı → Ollama modeli yükləyin (kod üçün `qwen2.5-coder` və ya `qwen3-coder` uyğundur). Bulud: Parametrlər → Bulud modelləri → OpenRouter, Groq və ya Gemini-nin pulsuz açarını yapışdırın.',
        '**Layihə.** «Yeni layihə» → kodu olan qovluq. Çatlar «Yeni çat» düyməsi ilə yaradılır; layihəyə klik yalnız onu açır.',
        '**Sorğu.** Tapşırığı sadə dillə yazın: «abunə formu əlavə et və işlədiyini yoxla». **Tools** düyməsini yandırın — onsuz model yalnız mətnlə cavab verir, faylları dəyişmir.',
        'İlk işə salınmada qurulum ustası dil, sxem və paketləri soruşur; hamısını sonradan dəyişmək olar.',
        '**Nə haradadır:** Çat, Fayllar, Məlumat və SSH — yuxarı paneldə; Agentlər, Servislər, Modellər və Plaginlər — sol yan panelin yuxarısında; Önizləmə, Kod rejimi və hesab — sağ yuxarıdakı nişanlar.',
      ],
      links: [
        { label: 'Modellər', view: 'models' },
        { label: 'Parametrlər', view: 'settings' },
        { label: 'Servislər', view: 'services' },
      ],
    },
    {
      id: 'chat', title: 'Çat və agent',
      lead: 'Seçilmiş layihə üzrə modellə söhbət. Daxiletmə sahəsinin üstündəki açarlar nələrə icazə verildiyini idarə edir.',
      table: [
        ['Tools', 'agent faylları oxuyur, axtarır, yaradır və dəyişir, tapşırıq yaradır və səhifələri yoxlayır'],
        ['Web', 'internetdə axtarış və səhifələrin URL ilə oxunması (`web_search`, `fetch_url`)'],
        ['Model', 'lokal və ya bulud (☁); seçim yadda saxlanılır'],
      ],
      items: [
        '**Layihə xəritəsi.** Model layihənin yığcam ağacını həmişə özü alır (kiçik lokal modellər üçün qısa, pəncərələrini doldurmasın deyə) — heç nəyi qoşmaq lazım deyil. Faylların məzmununu lazım olduqda alətlərlə oxuyur.',
        '**Enter** göndərir, **Shift+Enter** yeni sətir əlavə edir. Faylları və şəkilləri sancaqla və ya sürükləməklə əlavə edin.',
        '**Ekran görüntüsü → şablon:** vision-model şəkli təsvir edir, sonra alətli model maketi fayl kimi yaradır. Nümunə kimi göndərdiyiniz HTML və ya kod əsas götürülür.',
        'İş gedərkən «Çat» tabı pulsasiya edir, başlığın altında xətt axır, pəncərə başlığında isə ● görünür. Addımlar zənciri («Oxuyuram…», «Yazıram…») bir sətirdə yığılıb — bütün addımları görmək üçün üzərinə klikləyin.',
        'Xəta olduqda mesajın altında **«Yenidən cəhd et»** düyməsi çıxır; sizin mesajınızda da var (üzərinə gələndə).',
        '**İş necə gedir.** Agent məşğul olarkən çatın altında animasiyalı otto işarəsi olan canlı sətir görünür: hazırda nə edir, nə qədərdir işləyir və neçə token yaradılıb. Modelin mühakiməsi (varsa) yığılan «Mühakimə» blokundadır. Cavabın sonunda «Dəyişikliklər» kartı var: hansı fayllar yaradılıb, dəyişdirilib və ya silinib, neçə sətir əlavə olunub və ya çıxarılıb; HTML fayllarında önizləmədə açmaq düyməsi var.',
      ],
    },
    {
      id: 'tools', title: 'Agent nə edə bilir',
      lead: 'Modelin özü çağırdığı alətlər. Fayl əməliyyatları layihə qovluğu ilə məhdudlaşır.',
      table: [
        ['run_command', 'layihə qovluğunda əmr icra edir: servisləri qaldırmaq (`docker compose`), baza yaratmaq, paket quraşdırmaq, layihəni işə salmaq; uzun proseslər fona keçir'],
        ['read_skill_file', 'bacarıq dəstindəki arayış və ya şablonu oxuyur'],
        ['list_files / search_files', 'layihənin strukturu və məzmun üzrə sıralanmış axtarış'],
        ['read_file', 'faylı oxuyur; böyük fayllar hissə-hissə verilir — davamı `start_line`/`end_line` ilə'],
        ['write_file / append_file', 'faylları yaradır və dəyişir; böyükləri hissələrlə yazılır'],
        ['delete_file', 'fayl və ya qovluğu silir (layihənin kökü qorunur)'],
        ['create_task / plan_task', 'sağ paneldə tapşırıq və ya mərhələli plan yaradır'],
        ['web_search / fetch_url', 'saytları axtarır və oxuyur; səhifə məzmunu məlumatdır, əmr deyil'],
        ['preview_page', 'HTML-i real brauzerdə açır: JS xətaları, 375 px-də üfüqi sürüşmə, sınıq ankerlər və şəkillər, ekran görüntüsü'],
        ['run_in_page', 'səhifədə ssenari icra edir (form, menyu, düymələr) və həqiqətən nə baş verdiyini qaytarır'],
        ['use_skill', 'bacarıq yükləyir — ekspert qaydaları dəsti'],
      ],
      items: [
        '**Əmrlər standart olaraq sizin təsdiqinizlədir:** çatda əmr və **İcra et / Rədd et** düymələri olan kart görünür. Ayarlar → Agent → «Terminal əmrləri»: Soruş / Avto / Söndür. Sistemə zərər verə bilən əmrlər heç vaxt icra olunmur.',
        '**Nəticənin yoxlanması.** Səhifəni dəyişdikdən sonra agent onu açıb ssenariləri icra etməlidir; «yoxlanıldı» sözünə yalnız alət təsdiq edəndə icazə var. Microsoft Edge və ya Chrome quraşdırılmalıdır — əks halda agent dürüstcəsinə yoxlaya bilmədiyini bildirir.',
        'Layihədən kənara çıxa, faylı boş `content` ilə silə və ya fayla daxili yer tutucu yaza bilməz.',
      ],
    },
    {
      id: 'skills', title: 'Bacarıqlar (skills)',
      lead: 'Bacarıq — `SKILL.md` olan qovluqdur: müəyyən iş növü üçün qaydalar (dizayn, UI yoxlaması…). Uyğun olan sorğudakı açar sözlərə görə və ya `use_skill` çağırışı ilə yüklənir.',
      items: [
        '**Daxili:** Otto-nun bacarıqları (web-design, verify-ui, ux-design, accessibility, ux-copy, responsive-mobile, code-review, testing, security-review, git-commits) və Anthropic-in 14 rəsmi bacarığı (frontend-design, canvas-design, theme-factory, mcp-builder, claude-api, webapp-testing, skill-creator və s.; Apache 2.0, «Anthropic» nişanı ilə).',
        'Sorğuya ən çox iki uyğun bacarıq əlavə olunur; digərlərini agent `use_skill` ilə yükləyir, fayllarını `read_skill_file` ilə oxuyur. Bərabərlikdə layihənin bacarığı qalib gəlir, sonra sizinki, sonra Otto-nunku, sonra rəsmi.',
        '**«Bacarıqlar» düyməsi** Tools / Web yanında: axtarış, növlərə görə qruplar və işarələr. Dəst **layihə və model üçün** saxlanılır; «Ümumi dəstə qayıt» sıfırlayır.',
        '**Özünüzünkü:** `SKILL.md` faylını `<layihə>/.otto/skills/<ad>/` və ya tətbiq bazasının yanındakı `skills` qovluğuna qoyun. Başlıq: `name`, `description`, istəyə görə `triggers` və `category`.',
        '**Kitabxana:** Anthropic (Claude plaginləri, knowledge-work: satış, maliyyə, marketinq, hüquq, məlumat, mühəndislik…) və OpenAI-dən (playwright, Vercel/Netlify/Cloudflare-ə deploy, təhlükəsizlik, Jupyter, nitq…) daha ~300 rəsmi bacarıq, hamısı Apache 2.0 / MIT. «Bacarıqlar» düyməsində işarələyənə qədər söndürülüb. Figma və Claude Security bacarıqları daxil edilməyib (qapalı lisenziya).',
      ],
      links: [{ label: 'Parametrlər', view: 'settings' }],
    },
    {
      id: 'tasks', title: 'Mərhələli tapşırıqlar',
      items: [
        'Sağ panel: çek-listli tapşırıq. **«AI ilə plan»** tapşırığı mərhələlərə bölür; mərhələləri əl ilə də əlavə etmək olar. `plan_task` alətini çağırmayan kiçik lokal model də işləyir: cavabındakı nömrələnmiş siyahı mərhələlərə çevrilir.',
        '**▶ «Mərhələlərlə icra»:** hər mərhələ ayrıca, təzə kontekstlə gedir və özü işarələnir. **∥** ilə işarələnmiş (müstəqil, digər fayllar) mərhələlər paralel icra olunur — eyni anda neçəsi ayarlarda təyin edilir (1–4).',
        '**Nə baş verir.** Tapşırıq gedərkən daxiletmənin üstündəki zolaq mərhələni və agentin hazırda nə etdiyini göstərir, **Fasilə / Davam**, **Dayandır** və **Gedişat** düymələri ilə (tam jurnal «Agentlər» bölməsində, hər mərhələ «tapşırıq mərhələsi» kimi görünür).',
        '**Xətalar idarə olunur.** Pulsuz modelin sorğu limiti → mərhələ bir dəqiqə gözləyib təkrarlanır (5 dəfəyədək). Lokal modelin pozulmuş alət çağırışı → 3 dəfəyədək təkrar. Model kodu fayla yazmaq əvəzinə cavaba yapışdırırsa → yenidən xahiş olunur və «hazır» işarəsi qoyulmur; yenə yazmasa, tapşırıq xətayla dayanır.',
        'Xətadan və ya proqramın yenidən başlamasından sonra tapşırıqda **Təkrar et** / **Davam et** görünür; faylı dəyişmədən işarələnmiş mərhələnin öz **Təkrar et** düyməsi var. «Hazır» siyahısı yığılıb — başlığa klikləyin.',
        'Böyük işlər üçün agent `plan_task` ilə özü planlaya bilər. «Agentlər» bölməsi eyni tip işi fonda, açıq çatsız icra edir.',
        'Layihədə tamamlanmamış tapşırıqlar olduqda «Çat» nişanında onların sayı və brend işığı görünür (tapşırıq icra olunarkən yanıb-sönür). Sağdakı tapşırıq paneli açılışda həmişə yığılıdır.',
      ],
      links: [{ label: 'Agentlər', view: 'agents' }],
    },
    {
      id: 'context', title: 'Kontekst və metrikalar',
      lead: 'Model yalnız öz «pəncərəsinə» sığanı xatırlayır. Çatın altındakı sətir `istifadə / pəncərə` və sürəti (saniyədə token) göstərir; təfərrüat üçün üzərinə klikləyin.',
      items: [
        '**Rəng:** 70%-ə qədər yaşıl, 90%-ə qədər sarı, üstü qırmızı. Rəqəmin qarşısındakı `~` təxmini qiymət deməkdir (bulud provayderləri həmişə dəqiq tokeni bildirmir).',
        '**Yer qənaəti:** böyük fayllar hissə-hissə oxunur; pəncərə 60%-dən çox dolduqda alətlərin köhnə nəticələri qısa qeydlərlə əvəz olunur. Tapşırıq və son addımlar toxunulmaz qalır.',
        '**Pəncərə ölçüsü:** lokal modellər üçün 32k token (model çökərsə avtomatik yarıya düşür), bulud modelləri üçün hesablamada 64k.',
        '**Video yaddaş azdır?** Ollama-nı `OLLAMA_FLASH_ATTENTION=1` və `OLLAMA_KV_CACHE_TYPE=q8_0` ilə işə salın — keş təxminən iki dəfə az yer tutur.',
      ],
    },
    {
      id: 'cloud', title: 'Bulud modelləri',
      lead: 'Pulsuz tariflər: yalnız API açarı lazımdır. Açar bu kompüterdə saxlanılır və yadda saxlayanda yoxlanılır.',
      table: [
        ['OpenRouter', '`:free` işarəli modellər, kart lazım deyil; limit — gündəlik sorğular'],
        ['Groq', 'sürətli cavab, sorğu/token üzrə pulsuz limit'],
        ['Google Gemini', 'Google AI Studio-nun pulsuz tarifi'],
        ['Claude (Anthropic)', 'console.anthropic.com-dan ödənişli API açarı; doğma protokol, düşünmə səviyyəsi'],
        ['Grok (xAI)', 'console.x.ai-dan ödənişli açar (Groq ilə eyni deyil)'],
        ['Cerebras', 'çox sürətli Llama/Qwen, OpenRouter-dən ayrı öz pulsuz limiti ilə'],
        ['Mistral', 'Codestral, Devstral və Mistral modelləri; təcrübə üçün pulsuz tarif'],
        ['OpenCode Zen', 'pulsuz modellər, açarı xidmət verir'],
        ['Öz serveriniz', 'istənilən OpenAI-uyğun ünvan (LM Studio, llama.cpp…) — açar məcburi deyil'],
      ],
      items: [
        '**Limitlər provayderə görədir.** Bütün pulsuz OpenRouter modelləri bir limiti bölüşür, ona görə 429 zamanı agent açarınız varsa BAŞQA provayderin modelinə keçir (Groq, Gemini, Cerebras…); tapşırıq mərhələsi isə sadəcə gözləyib təkrarlayır.',
        '**Avtomatik keçid.** Model xəta qaytararsa (əlçatmaz, limit, yanlış sorğu) və ya 2 dəqiqə susarsa, agent əvvəlcə daha qısa sorğu ilə təkrarlayır, sonra başqa pulsuz modelə keçir (3 dəfəyə qədər) və bunu çatda yazır. Model seçicisi keçidi izləyir.',
        'Açar xətası (401/403) modeli dəyişmir — açarı Parametrlərdə düzəldin.',
        'Provayder limitləri Parametrlərdə açarın yanında göstərilir.',
      ],
      links: [{ label: 'Parametrlər → Bulud modelləri', view: 'settings' }],
    },
    {
      id: 'subscriptions', title: 'Abunə ilə Claude və Codex',
      lead: 'API açarı əvəzinə Claude Pro/Max və ya ChatGPT abunəniz: Otto bu kompüterdə quraşdırılmış rəsmi CLI-ni sizin girişinizlə işə salır.',
      items: [
        '**Qoşmaq:** Ayarlar → Modellər → «Abunə ilə Claude (CLI)» və/və ya «Abunə ilə Codex (CLI)». Açar dərhal saxlanılır; CLI daxil olmayıbsa, giriş dərhal brauzerdə açılır (çatdakı xətada da **Daxil ol** düyməsi var).',
        '**Lazımdır:** Claude Code (claude.ai/code) və ya Codex tətbiqi / `npm i -g @openai/codex`. Otto parolunuzu görmür: giriş provayderin səhifəsində olur.',
        '**Dəqiq versiyalar:** «sonnet / opus / haiku»-dan (hər xəttin sonuncusu) əlavə konkret versiya seçmək olar — Opus 5.5, Sonnet 5.5, Fable 5.1, Haiku 4.5 və Claude API açarınızın siyahısındakı digərləri. Model tarifdə yoxdursa, cavabı Sonnet verir.',
        '**Modellər:** «Claude (abunə)» — Sonnet, Opus, Haiku; «Codex (abunə)» — yalnız tarifinizdə olan modellər (gündə bir dəfə yoxlanılır). Girişi olmayan model avtomatik standart modelə keçir.',
        '**Limitlər:** tarif, istifadə payı və sıfırlanma vaxtı ayarlarda və daxiletmənin yanında görünür; hər cavabdan sonra kontekst sayğacı model versiyasını, pəncərəni, tokenləri və sürəti göstərir.',
        '**Qaydalar:** fayl redaktəsi Tools düyməsinə görə. Claude əmrləri yalnız «Avto» rejimində icra edir; Codex — öz sandbox-unda (yalnız layihə qovluğunda).',
        'Şəxsi istifadə üçün: girişinizi başqalarına verməyin.',
      ],
    },
    {
      id: 'projects', title: 'Yeni layihələr',
      lead: 'Layihələrin harada yaradıldığı və hansı başlanğıc fayllarının əlavə oluna biləcəyi.',
      items: [
        '**Layihələr qovluğu.** «Parametrlər → Layihələr qovluğu»: qovluğa bağlanmadan yaradılan yeni layihələr bura düşür. Mövcud layihələr öz yerində qalır.',
        '**Başlanğıc faylları.** «Yeni layihə» pəncərəsində `.gitignore` növünü (Node.js, Python, Laravel, PHP, Java, Go, Rust, .NET, Flutter, Ruby və ya yalnız IDE və ƏS faylları), lisenziyanı (MIT, Apache 2.0, GPL v3, AGPL v3, MPL 2.0, BSD, ISC, Unlicense) və `git init` seçmək olar. Mövcud fayllar heç vaxt üzərinə yazılmır. Apache, GPL, AGPL və MPL mətnləri rəsmi SPDX siyahısından yüklənir, internet lazımdır; internet yoxdursa `LICENSE`-də keçid olacaq.',
      ],
    },
    {
      id: 'files', title: 'Fayllar: redaktor və ağac',
      items: [
        'Ağac layihə növünə görə xidməti qovluqları gizlədir (`node_modules`, `vendor`, `target`, `dist`…). Fayl və tabları sürükləmək olar.',
        'Sintaksis işıqlandırması: JS/TS, JSON, CSS, HTML, Python, YAML, INI, Markdown, shell, SQL, PHP, NSIS.',
        '**Ctrl+F** redaktordan kənarda layihə üzrə qlobal axtarışdır, redaktorda faylda axtarır; **Ctrl+Shift+F** həmişə qlobaldır. Uyğunluqlar nəticələrdə və faylda işıqlandırılır.',
        'Əvəzləmə: faylda **Ctrl+H** / **Ctrl+R**, bütün layihədə **Ctrl+Alt+R**. **Ctrl+S** saxlayır, «Sync» ağacı diskdən yenidən oxuyur.',
        '**Marşrutlar:** «Marşrutlar» tabı marşrutları göstərir (Laravel, FastAPI, Express, Next.js); klik kontrolleri lazım olan sətirdə açır.',
        '«Kod» düyməsi fokus rejimini yandırır (çıxmaq üçün Esc). Daxili terminal pəncərənin altındadır.',
        '**Naviqator:** adı dəyişmə (F2), silmə (səbətə), dublikat, Windows Explorer-dən fayl və qovluqları ağaca sürükləmək; artıq mövcud ad qəbul edilmir. `.env` düyməsi faylı `.env.example`-dən yaradır — və ya AI-dan yazmasını xahiş edir.',
        '**İndeks və tamamlama:** layihə indekslənir (simvollar və sözlər); sürətli açma fayllarda qeyri-dəqiq axtarır, tamamlama layihənin öz adlarını, o cümlədən `.`, `->` və `::` sonrası üzvləri təklif edir.',
      ],
      links: [{ label: 'Fayllar', view: 'project' }],
    },
    {
      id: 'preview', title: 'Tətbiqin önizləməsi',
      lead: '«Önizləmə» tabı layihəni işə salır və birbaşa otto-nun içində — telefon, planşet və ya kompüter çərçivəsində göstərir.',
      items: [
        '**İşə salma.** «İşə sal» layihənin əmrini başladır (`npm run dev`, `php artisan serve`, `manage.py runserver` — fayllara görə müəyyən olunur; əmri dəyişə bilərsiniz). Dev-serverin ünvanı çıxışından götürülür və çərçivədə açılır. Adi HTML sayt üçün «Saytı aç» düyməsi var — proses lazım deyil.',
        '**Cihazlar.** iPhone, Pixel, Galaxy, iPad, noutbuk, Full HD və ya öz eni və hündürlüyünüzlə «Sərbəst ölçü». Çevirmə düyməsi portret və albom arasında keçir; miqyas — «Sığdır» və ya 50–125%. Səhifə cihazın həqiqi ekran enini görür, ona görə adaptiv üslublar telefondakı kimi işləyir.',
        '**Tam ekran.** Oxlu düymə önizləməni bütün pəncərəyə açır (çıxmaq üçün Esc). ↗ düyməsi ünvanı adi brauzerdə açır, terminal düyməsi işləyən serverin jurnalını göstərir.',
        'Server və proseslər tətbiqlə birlikdə dayandırılır. Çərçivədəki səhifə boşdursa, sayt yerləşdirməni qadağan etmiş ola bilər — onu brauzerdə açın.',
        '**Layihənin növü.** Önizləmə stekı fayllara görə müəyyən edir (Next.js, Vite, Laravel, Django, FastAPI, Docker Compose, Dev Container və s.), interfeysin olub-olmadığını göstərir və işə salma variantlarını təklif edir — məsələn, monorepodan yalnız frontend və ya `docker compose up`.',
        '**Mizanpaj və komponentlər.** Layihənin istənilən HTML/SVG faylı «Fayl» siyahısından açılır — server lazım deyil. Redaktordakı və agentin addımlar zəncirindəki «Önizləmə» düyməsi SI və ya insanın yazdığı faylı açır. Fayl diskdə dəyişəndə səhifə özü yenilənir. React/Vue/Svelte komponentlərinə dev-server vasitəsilə baxın: ünvan sətrinə səhifənin ünvanını yazın.',
      ],
    },
    {
      id: 'services', title: 'Servislər, alətlər və dillər',
      items: [
        '**Servislər:** istənilən servisin bir neçə nüsxəsi (verilənlər bazası, brokerlər, veb-müştərilər) avtomatik portlarla; birbaşa canlı jurnalla işə salma (docker compose), dayandırma, yenidən başlatma, kredensialların kopyalanması.',
        '**Alətlər:** Docker, Ollama, Git, GitHub CLI və dillərin winget ilə statusu və quraşdırılması.',
        '**Dillər:** dev-konteynerdə icra mühitləri; PHP üçün — genişlənmələr və Laravel paketləri.',
        '**Bir neçə PHP versiyası:** versiyaları quraşdır, yenidən quraşdır, sil; hər layihə öz versiyasını seçir və öz `php.ini`-si ola bilər. Composer layihənin PHP-sini avtomatik izləyir.',
        '**.env servisləri izləyir:** servis əlavə olunanda və ya port dəyişəndə layihənin `.env` faylı yenilənir.',
      ],
      links: [{ label: 'Servislər', view: 'services' }],
    },
    {
      id: 'data', title: 'Verilənlər bazaları («Data» bölməsi)',
      lead: 'PostgreSQL, MySQL və MariaDB üçün DataGrip üslubunda iş yeri: layihənin istifadə etdiyi hər şey özü tapılır və qoşulur — parol yığmaq lazım deyil.',
      items: [
        '**Avtomatik qoşulma:** «Servislər» bölməsindən və layihənin `.env` faylından (`DATABASE_URL`, `DB_*`, `POSTGRES_*`, `MYSQL_*`; konteyner adları `localhost` olur). Öz bağlantınızı **+** ilə əlavə edin; parol yalnız bu kompüterdə qalır. Yalnız lokal ünvanlara icazə verilir.',
        '**Solda ağac:** bazalar → filtrli cədvəllər və görünüşlər. Cədvələ klik onu açır, bazaya iki klik SQL konsolunu.',
        '**Cədvəl səhifəsi:** məlumat, struktur (sütunlar, açarlar, indekslər, xarici açarlar — klik əlaqəli cədvələ aparır) və DDL. Xanaya iki klik redaktədir (Enter saxlayır, Esc ləğv edir, NULL düyməsi NULL yazır); sətir əlavə etmə və silmə; başlığa görə sıralama; `WHERE` ifadəsi ilə filtr; 100-lük səhifələr; CSV və JSON ixracı. Sətirlər əsas açarla tapılır — açar yoxdursa cədvəl yalnız oxunur.',
        '**SQL konsolu:** rənglənmə, qoşulmuş bazanın cədvəl və sütun tamamlaması, **Ctrl+Enter** kursor altındakı (və ya seçilmiş) sorğunu icra edir, **EXPLAIN** (heç vaxt ANALYZE), sorğu tarixçəsi, nəticənin ixracı.',
      ],
    },
    {
      id: 'ssh', title: 'SSH / SFTP',
      lead: 'Bitvise ruhunda klient: serverlər, açarlar, fayl meneceri və əmrlər.',
      items: [
        '**Serverlər:** solda siyahı (ad, host, port, istifadəçi, başlanğıc qovluq). Açarla və ya parolla giriş; **«Parolu yadda saxla»** onu sistem anbarı ilə şifrələnmiş saxlayır (ekrana qayıtmır).',
        '**Açarlar:** parolla və ya parolsuz Ed25519 / RSA / ECDSA yaratma, öz açarını idxal, ictimai açarı kopyalama (serverdə `~/.ssh/authorized_keys`-ə əlavə edin). Şəxsi açarlar bu kompüterdə qalır.',
        '**Etibar:** ilk qoşulmada serverin barmaq izi göstərilir və təsdiq xahiş olunur. Tanış serverin açarı dəyişərsə, səssiz qoşulma yox, xəbərdarlıq olur.',
        '**Fayllar:** solda bu kompüter, sağda server; yolu əllə yazın (Enter), Ctrl ilə seçin, **→ / ←** düymələri və ya panellər arasında və Windows Explorer-dən sürükləməklə köçürün. Adı dəyiş, chmod, sil, yeni qovluq; iki klik mətn faylını redaktə üçün açır (Ctrl+S).',
        '**Ötürmə jurnalı** panellərin altında: hər yükləmə, endirmə və əməliyyat vaxtı, müddəti və dəqiq xəta mətni ilə; kopyalamaq və təmizləmək olar.',
        '**Əmrlər:** hər əmr serverdə icra olunur, cari qovluq saxlanılır, ↑/↓ tarixçə, Tab ilə tamamlama. İnteraktiv proqramlar (vim, top) dəstəklənmir.',
      ],
    },
    {
      id: 'plugins', title: 'Plaginlər',
      lead: 'Otto-ya daxil edilmiş əlavə alətlər; yan panel → Plaginlər bölməsində qoşulur, qoşulmuş plaginin nişanı sağ yuxarıda görünür.',
      items: [
        '**zeithub.coverty** — parollar, loginlər və keçidlər üçün şifrələnmiş seyf (AES-GCM 256 + PBKDF2), parol generatoru və JSON ixrac/idxal. Master parol bərpa olunmur; seyf 15 dəqiqə fəaliyyətsizlikdən sonra kilidlənir.',
        '**zeithub.alertas** — bildirişlər və səslə xatırlatma təqvimi və taymer; geriyə sayım plagin nişanında görünür. Otto işləyərkən işləyir.',
        'Hər ikisi orijinal genişlənmələr kimi görünür və məlumatı tətbiqin məlumat qovluğunda saxlayır.',
      ],
    },
    {
      id: 'models', title: 'Modellər',
      items: [
        'Tapşırıq üzrə pulsuz lokal modellər kataloqu (Ollama): çat, kod, mühakimə, şəkillər. İrəliləyişlə yükləmə və silmə; lokal modellər internetsiz işləyir.',
        'Ekran görüntüləri üçün vision-model (`qwen2.5vl`) lazımdır; agent üçün alətləri dəstəkləyən model.',
      ],
      links: [{ label: 'Modellər', view: 'models' }],
    },
    {
      id: 'git', title: 'Git və hesablar',
      items: [
        'Çoxhesablılıq (yuxarı sağda): hər hesabın öz layihələri və çatları var.',
        'Token ilə hesab əlavə etmə, repozitoriyaların klonlanması, budaqların dəyişdirilməsi və yaradılması.',
      ],
    },
    {
      id: 'look', title: 'Görünüş və dillər',
      items: [
        'Parametrlər → 13 rəng sxemi (o cümlədən Dracula, Nord, Tokyo Night, One Dark, Gruvbox, Catppuccin, Solarized). Vurğu düymələrindəki mətn kontrasta görə seçilir.',
        'İnterfeys və bu sənədlər 6 dildə mövcuddur: Русский, English, Azərbaycan, ქართული, Italiano, Español.',
      ],
      links: [{ label: 'Parametrlər', view: 'settings' }],
    },
    {
      id: 'keys', title: 'İsti düymələr',
      table: [
        ['Enter / Shift+Enter', 'mesajı göndər / yeni sətir'],
        ['Ctrl+F', 'axtarış (redaktorda — fayl üzrə, kənarda — layihə üzrə)'],
        ['Ctrl+Shift+F', 'qlobal axtarış'],
        ['Ctrl+H / Ctrl+R', 'faylda əvəzləmə'],
        ['Ctrl+Alt+R', 'qlobal əvəzləmə'],
        ['Ctrl+S', 'faylı saxla'],
        ['Ctrl+K', 'sürətli axtarış'],
        ['Ctrl+Shift+O', 'faylın simvolları'],
        ['Ctrl+C / X / V / A / Z', 'köçür, kəs, yapışdır, hamısını seç, geri al — hər yerdə (daxiletmə sahələrində və naviqatorda da)'],
        ['↑ / ↓ terminalda', 'əmr tarixçəsi (layihə üzrə saxlanır, yazılmamış mətn qaytarılır)'],
        ['Tab SSH konsolunda', 'serverdəki fayl və əmr adlarını tamamlayır'],
        ['F2 / Delete naviqatorda', 'adı dəyiş / sil (səbətə)'],
        ['Esc', 'pəncərəni bağla / fokus rejimindən çıx'],
      ],
    },
    {
      id: 'privacy', title: 'Məlumat və təhlükəsizlik',
      items: [
        'SSH açarları və saxlanılmış parollar yalnız bu kompüterdə saxlanılır (parollar sistem anbarı ilə şifrələnir).',
        'Layihələr, çatlar, tapşırıqlar və açarlar lokal olaraq tətbiq məlumatları qovluğunda saxlanılır. Lokal modellər şəbəkəyə heç nə göndərmir.',
        'Bulud modelləri yalnız sorğuya düşəni alır: mesajınızı, çat tarixçəsini və agentin oxuduğu faylların məzmununu.',
        'Agent layihə qovluğundan kənara çıxmır. Tətbiq serveri yalnız `127.0.0.1` üzərində dinləyir.',
      ],
    },
    {
      id: 'faq', title: 'Nəsə işləmirsə',
      faq: [
        ['Abunə ilə Claude / Codex: «daxil olmamısınız»', 'Mesajda və ya Ayarlar → Modellər bölməsində **Daxil ol** düyməsini basın: CLI provayderin giriş səhifəsini brauzerdə açacaq. Sonra sorğunu təkrarlayın.'],
        ['Codex: «model mövcud deyil və ya giriş yoxdur»', 'Bu model tarifinizdə yoxdur. Otto onu siyahıdan çıxaracaq və standart modellə cavab verəcək.'],
        ['Mərhələ işarələnib, amma fayl dəyişməyib', 'Model `write_file` çağırmaq əvəzinə kodu cavaba yapışdırıb (cavabda «fayllar DƏYİŞMƏYİB»). İndi belə mərhələlər təkrarlanır və işarə qoyulmur; köhnələr üçün mərhələdəki **Təkrar et** düyməsini basın. Kiçik lokal modellər bunu tez-tez edir — fayl redaktəsi üçün daha böyük və ya bulud modeli seçin.'],
        ['SSH: «Authentication failed»', 'Parol səhvdir və ya ictimai açar həmin istifadəçinin `~/.ssh/authorized_keys` faylında yoxdur. İctimai açarı SSH açarları səhifəsindən kopyalayın.'],
        ['Agent mətnlə cavab verir, faylları dəyişmir', '**Tools** açarının yandığını və modelin alətləri dəstəklədiyini yoxlayın (OpenRouter-də yalnız tools işarəli modellər). Zəif modelləri əvəz edin: `qwen3-coder`, `qwen2.5-coder`.'],
        ['«Ollama əlçatmazdır» / lokal model yoxdur', 'Ollama-nın işlədiyinə (`ollama serve`) və `http://localhost:11434` ünvanında dinlədiyinə əmin olun; siyahını model menyusundakı düymə ilə yeniləyin.'],
        ['Lokal model çökdü («terminated», «exit status»)', 'Adətən yaddaş çatmır: kontekst pəncərəsi avtomatik yarıya düşür və sorğu təkrarlanır. Tez-tez baş verirsə, daha kiçik model götürün və ya `OLLAMA_KV_CACHE_TYPE=q8_0` yandırın.'],
        ['Bulud modeli susur və ya 429 qaytarır', 'Pulsuz modellər növbəyə düşür və gündəlik limitləri var. Gözləyin (sıfırlanma vaxtı xətada göstərilir) — ya da agent özü başqa modelə keçər. Limitlər Parametrlərdə görünür.'],
        ['Bulud modelindən «invalid request»', 'Bəzi modellər sorğu formatına daha ciddi yanaşır. Agent daha qısa sorğu ilə təkrarlayıb başqa modelə keçir; «Yenidən cəhd et» yenidən başladır.'],
        ['«Səhifə yoxlanıla bilmədi»', '`preview_page` üçün Microsoft Edge və ya Google Chrome lazımdır. Brauzer yoxdursa, agent yoxlamanın mümkün olmadığını bildirir.'],
        ['.exe quraşdırıcı açılmır', 'Windows Smart App Control imzasız proqramları bloklayır. Quraşdırıcını GitHub Actions-də yığın və ya sertifikatla imzalayın; inkişaf zamanı tətbiqi `npm start` ilə işə salın.'],
        ['Axtarış node_modules-a baxmır', 'Xidməti qovluqlar layihə növünə görə qəsdən gizlədilib; lazım olsa, o faylları əl ilə açın.'],
      ],
    },
  ],
};

export default text;
