import type { HelpText } from './types';

const text: HelpText = {
  title: 'Documentation',
  subtitle: 'zeithub.otto is a local AI development studio: chat, a tool-using agent, editor, tasks, services and models in one window.',
  searchPlaceholder: 'Search the documentation…',
  contents: 'Contents',
  nothing: 'Nothing found. Try another word.',
  inMain: 'Opens in the main window',
  overview: 'Overview',
  prev: 'Previous',
  next: 'Next',
  openWindow: 'Open in a separate window',
  quick: [
    { n: '1', title: 'Connect a model', text: 'Local Ollama (the Models tab) or a free cloud key in Settings.', view: 'models' },
    { n: '2', title: 'Open a project', text: '“New project” → pick a folder. A project expands on click, chats live inside it.', view: 'chat' },
    { n: '3', title: 'Give it a job', text: 'Tell the chat what to do. The agent reads files, writes code and checks the page in a browser.', view: 'chat' },
  ],
  sections: [
    {
      id: 'start', title: 'Quick start',
      lead: 'Three steps from installation to a first result.',
      items: [
        '**Model.** Local: the Models tab → download an Ollama model (`qwen2.5-coder` or `qwen3-coder` suit code). Cloud: Settings → Cloud models → paste a free OpenRouter, Groq or Gemini key.',
        '**Project.** “New project” → a folder with code. Start chats with “New chat”; clicking a project only expands it.',
        '**Request.** Describe the job in plain words: “add a subscribe form and check that it works”. Turn **Tools** on — without it the model only answers in text and changes no files.',
        'On first launch the setup wizard asks for language, scheme and packages; all of it can be changed later.',
        '**Where things are:** Chat, Files, Data and SSH are in the top bar; Agents, Services, Models and Plugins are at the top of the left sidebar; Preview, Code mode and the account are the icons on the top right.',
      ],
      links: [
        { label: 'Models', view: 'models' },
        { label: 'Settings', view: 'settings' },
        { label: 'Services', view: 'services' },
      ],
    },
    {
      id: 'chat', title: 'Chat and the agent',
      lead: 'A conversation with a model about the selected project. The toggles above the input control what it can do.',
      table: [
        ['Tools', 'the agent reads, searches, creates and edits files, creates tasks and checks pages'],
        ['Web', 'web search and reading pages by URL (`web_search`, `fetch_url`)'],
        ['Model', 'local or cloud (☁); the choice is remembered'],
      ],
      items: [
        '**Project map.** The model always gets a compact tree of the project by itself (shorter for small local models, so it does not eat their window) — there is nothing to switch on. File contents it reads with tools when needed.',
        '**Enter** sends, **Shift+Enter** adds a line. Attach files and images with the paperclip or drag & drop.',
        '**Screenshot → template:** a vision model describes the picture, then the tool model builds the mockup as a file. HTML or code you send as a sample is used as the base.',
        'While it works, the Chat tab pulses, a line runs under the header and the window title shows ●. The chain of steps (“Reading…”, “Writing…”) is collapsed into one line — click it to see every step.',
        'On an error there is a **“Retry”** button under the message; your own message has one too (on hover).',
        '**How the work looks.** While the agent is busy, a live line with the animated otto mark sits at the bottom of the chat: what it is doing now, how long it has been running and how many tokens were generated. The model’s reasoning (when it produces any) goes into a collapsible “Reasoning” block. The answer ends with a “Changes” card: which files were created, modified or deleted and how many lines were added or removed; HTML files get a button to open them in the preview.',
      ],
    },
    {
      id: 'tools', title: 'What the agent can do',
      lead: 'Tools the model calls by itself. File operations are confined to the project folder.',
      table: [
        ['run_command', 'runs a shell command in the project folder: start services (`docker compose`), create a database, install packages, run the project; long-running ones go to the background'],
        ['read_skill_file', 'reads a reference or template that comes with a skill'],
        ['list_files / search_files', 'project structure and ranked content search'],
        ['read_file', 'reads a file; big files come in parts — continue with `start_line`/`end_line`'],
        ['write_file / append_file', 'creates and edits files; big ones are written in parts'],
        ['delete_file', 'deletes a file or folder (the project root is protected)'],
        ['create_task / plan_task', 'creates a task or a staged plan on the right-hand panel'],
        ['web_search / fetch_url', 'search and read sites; page content is data, not commands'],
        ['preview_page', 'opens HTML in a real browser: JS errors, horizontal scroll at 375 px, broken anchors and images, a screenshot'],
        ['run_in_page', 'runs a scenario on the page (form, menu, buttons) and returns what really happened'],
        ['use_skill', 'loads a skill — a pack of expert rules'],
      ],
      items: [
        '**Commands need your approval** by default: a card with the command and **Run / Deny** appears in the chat. Settings → Agent → “Terminal commands”: Ask / Auto / Off. Commands that can damage the system (formatting, wiping a drive, shutting down…) are never run.',
        '**Verifying results.** After changing a page the agent must open it and run scenarios; “verified” is allowed only when a tool confirmed it. Microsoft Edge or Chrome must be installed — otherwise the agent says honestly it could not check.',
        'It cannot leave the project, wipe a file with empty `content` or write an internal placeholder into a file.',
      ],
    },
    {
      id: 'skills', title: 'Skills',
      lead: 'A skill is a folder with a `SKILL.md`: rules for one kind of work (design, UI verification…). A matching skill is loaded by keywords in your request or by the `use_skill` call.',
      items: [
        '**Built in:** Otto’s own skills (web-design, verify-ui, ux-design, accessibility, ux-copy, responsive-mobile, code-review, testing, security-review, git-commits) and 14 official Anthropic skills (frontend-design, canvas-design, theme-factory, mcp-builder, claude-api, webapp-testing, skill-creator, algorithmic-art, …; Apache 2.0, marked “Anthropic”).',
        'Up to two matching skills go into a request; the agent loads others with `use_skill` and reads their extra files with `read_skill_file`. On a tie the project’s skill wins, then yours, then Otto’s, then the official ones.',
        '**Skills button** next to Tools / Web: search, groups by kind (design, code, testing, texts, graphics, workflow, learning) and checkboxes. The set is saved **per project and model** — switch the model and its own set comes back; “Back to the common set” resets it.',
        '**Your own:** a `SKILL.md` in `<project>/.otto/skills/<name>/` (this project) or in the `skills` folder next to the app database (all projects). Header: `name`, `description` (one line or a YAML block), optional `triggers` and `category`.',
        '**Library:** about 300 more official skills from Anthropic (Claude plugins, knowledge-work plugins: sales, finance, marketing, legal, data, engineering…) and OpenAI (playwright, deploy to Vercel/Netlify/Cloudflare, security, Jupyter, speech…), all Apache 2.0 / MIT. They are off until you tick them in the Skills button, so they do not weigh on requests. Figma, Notion-licensed and Claude Security skills are not included (closed licences).',
      ],
      links: [{ label: 'Settings', view: 'settings' }],
    },
    {
      id: 'tasks', title: 'Tasks by stages',
      items: [
        'The right-hand panel: a task with a checklist. **“Plan with AI”** splits the task into steps; you can add steps by hand. A small local model that skips the `plan_task` tool still works: a plain numbered list in its answer is turned into steps.',
        '**▶ “Run steps”:** every step runs separately with fresh context (goal, checklist and results of earlier steps) and ticks itself off. Steps marked **∥** (independent, other files) run in parallel — the number at once is set in Settings (1–4).',
        '**What is going on.** While a task runs, a bar above the input shows the step and what the agent does right now (“Writing src/app.ts · 1:23”) with **Pause / Resume**, **Stop** and **Progress** (the full log in the Agents tab, where every step is listed as “task step”).',
        '**Failures are handled.** Request limit of a free model → the step waits a minute and repeats (up to 5 times). A garbled tool call of a local model → repeated up to 3 times. A model that pastes code into the answer instead of writing the file → asked again, and never ticked off as done; if it still does not write, the task stops with an error.',
        'After an error or an app restart the task shows **Retry** / **Continue**; a step ticked off without any file change has its own **Retry**. The “Done” list is collapsed — click its header.',
        'For big jobs the agent can plan on its own with `plan_task`. The Agents tab runs the same kind of job in the background, without an open chat.',
        'When the project has unfinished tasks, the Chat tab shows their number and the brand glow (it pulses while one runs). The task panel on the right always starts collapsed.',
      ],
      links: [{ label: 'Agents', view: 'agents' }],
    },
    {
      id: 'context', title: 'Context and metrics',
      lead: 'A model only remembers what fits in its “window”. The row under the chat shows `used / window` and speed (tokens per second); click it for details.',
      items: [
        '**Colour:** green up to 70%, yellow up to 90%, red above. A `~` before the number is an estimate (cloud providers do not always report exact tokens).',
        '**Saving space:** big files are read in parts; once the window is over 60% full, old tool results are replaced by short notes. The task and the latest steps stay intact.',
        '**Window size:** 32k tokens for local models (halved automatically if the model crashes), 64k assumed for cloud ones.',
        '**Short on VRAM?** Start Ollama with `OLLAMA_FLASH_ATTENTION=1` and `OLLAMA_KV_CACHE_TYPE=q8_0` — the cache takes about half the space.',
      ],
    },
    {
      id: 'cloud', title: 'Cloud models',
      lead: 'Free tiers: all you need is an API key. The key is stored on this computer and verified when saved.',
      table: [
        ['OpenRouter', 'models marked `:free`, no card needed; the limit is requests per day'],
        ['Groq', 'fast inference with a free request/token limit'],
        ['Google Gemini', 'the free tier of Google AI Studio'],
        ['Claude (Anthropic)', 'paid API key from console.anthropic.com; native protocol, reasoning effort'],
        ['Grok (xAI)', 'paid key from console.x.ai (not the same as Groq)'],
        ['Cerebras', 'very fast Llama/Qwen with its own free limit, separate from OpenRouter'],
        ['Mistral', 'Codestral, Devstral and Mistral models; free tier for experiments'],
        ['OpenCode Zen', 'free models, the key is issued by the service'],
        ['Custom server', 'any OpenAI-compatible address (LM Studio, llama.cpp…) — a key is optional'],
      ],
      items: [
        '**Limits are per provider.** All free OpenRouter models share one limit, so on a 429 the agent moves to a model of ANOTHER provider (Groq, Gemini, Cerebras…) when you have its key; a task step simply waits and repeats.',
        '**Automatic fallback.** If a model returns an error (unavailable, rate limit, invalid request) or is silent for 2 minutes, the agent first retries with a smaller request, then takes another free model (up to 3 times) and says so in the chat. The model picker follows the switch.',
        'A key error (401/403) does not switch models — fix the key in Settings.',
        'Provider limits are shown next to the key in Settings.',
      ],
      links: [{ label: 'Settings → Cloud models', view: 'settings' }],
    },
    {
      id: 'subscriptions', title: 'Claude and Codex by subscription',
      lead: 'Use your own Claude Pro/Max or ChatGPT plan instead of an API key: Otto runs the official CLI installed on this computer under your login.',
      items: [
        '**Turn on:** Settings → Models → “Claude via subscription (CLI)” and/or “Codex via subscription (CLI)”. The switch is saved at once; if the CLI is not signed in, the sign-in opens in the browser right away (the chat error also has a **Sign in** button).',
        '**Needed:** Claude Code (claude.ai/code) or the Codex app / `npm i -g @openai/codex`. Otto never sees your password: signing in happens on the provider’s page.',
        '**Exact versions:** besides “sonnet / opus / haiku” (the latest of each line) you can pick a specific one — Opus 5.5, Sonnet 5.5, Fable 5.1, Haiku 4.5 and others your Claude API key lists. If the plan does not include a model, the answer comes from Sonnet.',
        '**Models:** “Claude (subscription)” — Sonnet, Opus, Haiku; “Codex (subscription)” — only the models your plan can use (checked once a day). A model with no access falls back to the default one by itself.',
        '**Limits:** plan, used share and reset time are shown in Settings and next to the input; after each answer the context meter shows the model version, window, tokens and speed.',
        '**Rules:** file edits follow the Tools toggle. Claude runs commands only in the “Auto” terminal mode; Codex runs them inside its own sandbox (only in the project folder). API keys in the environment are ignored so your plan is used.',
        'For your own use: do not share your access with other people.',
      ],
    },
    {
      id: 'projects', title: 'New projects',
      lead: 'Where projects are created and which starter files to add.',
      items: [
        '**Projects folder.** “Settings → Projects folder”: new projects created without a bound folder go here. Existing projects stay where they are.',
        '**Starter files.** The “New project” dialog can add a `.gitignore` (Node.js, Python, Laravel, PHP, Java, Go, Rust, .NET, Flutter, Ruby or IDE/OS files only), a license (MIT, Apache 2.0, GPL v3, AGPL v3, MPL 2.0, BSD, ISC, Unlicense) and run `git init`. Existing files are never overwritten. The Apache, GPL, AGPL and MPL texts are downloaded from the official SPDX list, which needs internet; offline, `LICENSE` gets a link instead.',
      ],
    },
    {
      id: 'files', title: 'Files: editor and tree',
      items: [
        'The tree hides service folders by project type (`node_modules`, `vendor`, `target`, `dist`…). Files and tabs can be dragged.',
        'Syntax highlighting: JS/TS, JSON, CSS, HTML, Python, YAML, INI, Markdown, shell, SQL, PHP, NSIS.',
        '**Ctrl+F** outside the editor is a global project search, inside it searches the file; **Ctrl+Shift+F** is always global. Matches are highlighted in results and in the file.',
        'Replace: **Ctrl+H** / **Ctrl+R** in a file, **Ctrl+Alt+R** across the project. **Ctrl+S** saves, “Sync” re-reads the tree from disk.',
        '**Routes:** the “Routes” tab lists routes (Laravel, FastAPI, Express, Next.js); a click opens the controller at the right line.',
        'The “Code” button enables focus mode (Esc exits). The built-in terminal is at the bottom of the window.',
        '**Explorer:** rename (F2), delete (to the recycle bin), duplicate, drag files and folders from Windows Explorer into the tree; a name that already exists is refused. A `.env` button creates the file from `.env.example` — or asks the AI to write it.',
        '**Index and completion:** the project is indexed (symbols and words); quick open finds files fuzzily and completion offers the project’s own names, including members after `.`, `->` and `::`.',
      ],
      links: [{ label: 'Files', view: 'project' }],
    },
    {
      id: 'preview', title: 'App preview',
      lead: 'The Preview tab runs the project and shows it right inside otto — in a phone, tablet or desktop frame.',
      items: [
        '**Running.** “Run” starts the project’s command (`npm run dev`, `php artisan serve`, `manage.py runserver` — detected from the files; you can change it). The dev server’s address is picked up from its output and opened in the frame. A plain HTML site has an “Open the site” button — no process needed.',
        '**Devices.** iPhone, Pixel, Galaxy, iPad, laptop, Full HD or “Responsive” with your own width and height. The rotate button switches portrait and landscape; zoom is “Fit” or 50–125%. The page sees the real screen width of the device, so responsive styles behave as on a phone.',
        '**Full screen.** The arrows button expands the preview over the whole window (Esc exits). The ↗ button opens the address in a regular browser, the terminal button shows the running server’s log.',
        'The server and its processes are stopped together with the app. If the page in the frame stays blank, the site may forbid embedding — open it in the browser.',
        '**What kind of project.** The preview recognises the stack from the files (Next.js, Vite, Laravel, Django, FastAPI, Docker Compose, Dev Container, …), shows whether there is a UI, and offers ways to start it — for example just the front end of a monorepo, or `docker compose up`.',
        '**Markup and components.** Any HTML/SVG file of the project opens from the “File” list — no server needed. The “Preview” button in the editor and in the agent’s step chain opens the file written by the AI or a person. When the file changes on disk the page reloads by itself. React/Vue/Svelte components are viewed through the dev server: type the address of the page in the address bar.',
      ],
    },
    {
      id: 'services', title: 'Services, tools and languages',
      items: [
        '**Services:** several instances of any service (databases, brokers, web clients) with automatic ports; start one by one with a live log (docker compose), stop, restart, copy credentials.',
        '**Tools:** status and installation of Docker, Ollama, Git, GitHub CLI and languages through winget.',
        '**Languages:** runtimes in the dev container; for PHP — extensions and Laravel packages.',
        '**Several PHP versions:** install, reinstall or remove versions; every project picks its own version and can have its own `php.ini`. Composer follows the project’s PHP automatically.',
        '**.env follows the services:** when a service is added or its port changes, the project’s `.env` is updated.',
      ],
      links: [{ label: 'Services', view: 'services' }],
    },
    {
      id: 'data', title: 'Databases (Data tab)',
      lead: 'A DataGrip-style workspace for PostgreSQL, MySQL and MariaDB: everything the project uses is found and connected by itself — no password typing.',
      items: [
        '**Automatic connections:** taken from the Services tab and from the project’s `.env` (`DATABASE_URL`, `DB_*`, `POSTGRES_*`, `MYSQL_*`; container host names become `localhost`). Add your own with **+**; its password stays on this computer. Only local addresses are allowed.',
        '**Tree on the left:** databases → tables and views with a filter. Click a table to open it; double-click a database for a SQL console.',
        '**Table tab:** data, structure (columns, keys, indexes, foreign keys — a click goes to the referenced table) and DDL. Double-click a cell to edit it (Enter saves, Esc cancels, the NULL button sets NULL); add or delete a row; sort by a header; filter with a `WHERE` expression; pages of 100; export CSV or JSON. Rows are found by the primary key — without one the table is read-only.',
        '**SQL console:** highlighting, completion of tables and columns of the connected database, **Ctrl+Enter** runs the statement under the cursor (or the selection), **EXPLAIN** (never ANALYZE), query history, export of the result.',
      ],
    },
    {
      id: 'ssh', title: 'SSH / SFTP',
      lead: 'A client in the spirit of Bitvise: servers, keys, a file manager and commands.',
      items: [
        '**Servers:** a list on the left (name, host, port, user, start folder). Log in by key or by password; **Remember password** stores it encrypted with the system store (it never comes back to the screen).',
        '**Keys:** generate Ed25519 / RSA / ECDSA with or without a passphrase, import your own, copy the public key (add it to `~/.ssh/authorized_keys` on the server). Private keys stay on this computer.',
        '**Trust:** the first time a server shows its fingerprint and asks you to confirm. If the key of a known server changes you get a warning and no silent connection.',
        '**Files:** this computer on the left, the server on the right; type a path by hand (Enter), select with Ctrl-click, move with the **→ / ←** buttons or by dragging between panes or from Windows Explorer. Rename, chmod, delete, new folder; a double click opens a text file for editing (Ctrl+S).',
        '**Transfer log** under the panes: every upload, download and operation with time, duration and the exact error text; copy or clear it.',
        '**Commands:** each command runs on the server, the current folder is kept, ↑/↓ history, Tab completion. Interactive programs (vim, top) are not supported.',
      ],
    },
    {
      id: 'plugins', title: 'Plugins',
      lead: 'Extra tools built into Otto, switched on in the sidebar → Plugins; an enabled plugin gets an icon on the top right.',
      items: [
        '**zeithub.coverty** — an encrypted vault for passwords, logins and links (AES-GCM 256 + PBKDF2) with a password generator and JSON export/import. The master password cannot be recovered; the vault locks after 15 minutes of inactivity.',
        '**zeithub.alertas** — a reminders calendar and a timer with desktop notifications and sound; the countdown is shown on the plugin icon. Works while Otto is running.',
        'Both look like the original extensions and keep their data in the app data folder.',
      ],
    },
    {
      id: 'models', title: 'Models',
      items: [
        'A catalog of free local models (Ollama) by task: chat, code, reasoning, vision. Download with progress and deletion; local models work offline.',
        'Screenshots need a vision model (`qwen2.5vl`); the agent needs a model with tool support.',
      ],
      links: [{ label: 'Models', view: 'models' }],
    },
    {
      id: 'git', title: 'Git and accounts',
      items: [
        'Multi-account (top right): every account has its own projects and chats.',
        'Add an account by token, clone repositories, switch and create branches.',
      ],
    },
    {
      id: 'look', title: 'Appearance and languages',
      items: [
        'Settings → 13 colour schemes (including Dracula, Nord, Tokyo Night, One Dark, Gruvbox, Catppuccin, Solarized). Text on accent buttons is chosen for contrast.',
        'The interface and this documentation come in 6 languages: Русский, English, Azərbaycan, ქართული, Italiano, Español.',
      ],
      links: [{ label: 'Settings', view: 'settings' }],
    },
    {
      id: 'keys', title: 'Hotkeys',
      table: [
        ['Enter / Shift+Enter', 'send a message / new line'],
        ['Ctrl+F', 'search (in the editor — the file, outside — the project)'],
        ['Ctrl+Shift+F', 'global search'],
        ['Ctrl+H / Ctrl+R', 'replace in a file'],
        ['Ctrl+Alt+R', 'global replace'],
        ['Ctrl+S', 'save the file'],
        ['Ctrl+K', 'quick search'],
        ['Ctrl+Shift+O', 'file symbols'],
        ['Ctrl+C / X / V / A / Z', 'copy, cut, paste, select all, undo everywhere (also in inputs and the explorer)'],
        ['↑ / ↓ in a terminal', 'command history (kept per project, your unfinished text is restored)'],
        ['Tab in the SSH console', 'completes file and command names on the server'],
        ['F2 / Delete in the explorer', 'rename / delete (to the recycle bin)'],
        ['Esc', 'close a dialog / leave focus mode'],
      ],
    },
    {
      id: 'privacy', title: 'Data and security',
      items: [
        'SSH keys and saved passwords are stored only on this computer (passwords are encrypted with the system store).',
        'Projects, chats, tasks and keys are stored locally, in the app data folder. Local models send nothing over the network.',
        'Cloud models receive only what is in the request: your message, the chat history and the contents of files the agent read.',
        'The agent stays inside the project folder. The app server listens on `127.0.0.1` only.',
      ],
    },
    {
      id: 'faq', title: 'When something does not work',
      faq: [
        ['Claude / Codex by subscription: “not signed in”', 'Press **Sign in** in the message or in Settings → Models: the CLI opens the provider’s sign-in page in the browser. Then repeat the request.'],
        ['Codex: “model does not exist or you do not have access”', 'That model is not in your plan. Otto removes it from the list and answers with your plan’s default model.'],
        ['A step is ticked off but no file changed', 'The model pasted code into the answer instead of calling `write_file` (“files NOT changed” in the answer). Such steps are now repeated and never ticked; for old ones use **Retry** on the step. Small local models do this often — use a bigger or cloud model for editing.'],
        ['SSH: “Authentication failed”', 'Wrong password, or the public key is not in `~/.ssh/authorized_keys` of that user. Copy the public key from the SSH keys page.'],
        ['The agent answers in text and changes no files', 'Make sure the **Tools** toggle is on and the model supports tools (on OpenRouter only models marked tools). Replace weak models: `qwen3-coder`, `qwen2.5-coder`.'],
        ['“Ollama is unavailable” / no local models', 'Make sure Ollama is running (`ollama serve`) on `http://localhost:11434`; refresh the list with the button in the model dropdown.'],
        ['A local model crashed (“terminated”, “exit status”)', 'Usually out of memory: the context window is halved automatically and the request is retried. If it repeats — use a smaller model or enable `OLLAMA_KV_CACHE_TYPE=q8_0`.'],
        ['A cloud model is silent or returns 429', 'Free models queue requests and have daily limits. Wait (the reset time is in the error) — or the agent switches to another model itself. Limits are shown in Settings.'],
        ['“invalid request” from a cloud model', 'Some models are stricter about the request format. The agent retries with a smaller request and switches to another model; “Retry” starts over.'],
        ['“Could not check the page”', '`preview_page` needs Microsoft Edge or Google Chrome. Without a browser the agent says the check is impossible.'],
        ['The .exe installer does not start', 'Windows Smart App Control blocks unsigned programs. Build the installer in GitHub Actions or sign it with a certificate; during development run the app with `npm start`.'],
        ['Search does not look into node_modules', 'Service folders are hidden by project type on purpose; open such files by hand if you need them.'],
      ],
    },
  ],
};

export default text;
