import type { HelpText } from './types';

const text: HelpText = {
  title: 'Documentazione',
  subtitle: 'zeithub.otto è uno studio di sviluppo locale con IA: chat, agente con strumenti, editor, attività, servizi e modelli in una sola finestra.',
  searchPlaceholder: 'Cerca nella documentazione…',
  contents: 'Indice',
  nothing: 'Nessun risultato. Prova un’altra parola.',
  inMain: 'Si apre nella finestra principale',
  overview: 'Panoramica',
  prev: 'Precedente',
  next: 'Successivo',
  openWindow: 'Apri in una finestra separata',
  quick: [
    { n: '1', title: 'Collega un modello', text: 'Ollama in locale (scheda «Modelli») o una chiave cloud gratuita nelle Impostazioni.', view: 'models' },
    { n: '2', title: 'Apri un progetto', text: '«Nuovo progetto» → scegli una cartella. Il progetto si espande al clic, le chat sono al suo interno.', view: 'chat' },
    { n: '3', title: 'Assegna un compito', text: 'Scrivi nella chat cosa fare. L’agente legge i file, scrive il codice e controlla la pagina in un browser.', view: 'chat' },
  ],
  sections: [
    {
      id: 'start', title: 'Avvio rapido',
      lead: 'Tre passi dall’installazione al primo risultato.',
      items: [
        '**Modello.** In locale: scheda «Modelli» → scarica un modello Ollama (per il codice vanno bene `qwen2.5-coder` o `qwen3-coder`). Nel cloud: Impostazioni → Modelli cloud → incolla una chiave gratuita di OpenRouter, Groq o Gemini.',
        '**Progetto.** «Nuovo progetto» → una cartella con il codice. Le chat si creano con «Nuova chat»; un clic sul progetto lo espande soltanto.',
        '**Richiesta.** Descrivi il lavoro a parole tue: «aggiungi un modulo di iscrizione e verifica che funzioni». Attiva **Tools**: senza, il modello risponde solo con testo e non modifica i file.',
        'Al primo avvio la procedura guidata chiede lingua, schema e pacchetti; tutto si può cambiare in seguito.',
        '**Dove si trova cosa:** Chat, File, Dati e SSH sono nella barra in alto; Agenti, Servizi, Modelli e Plugin in cima alla barra laterale sinistra; Anteprima, Modalità codice e account sono le icone in alto a destra.',
      ],
      links: [
        { label: 'Modelli', view: 'models' },
        { label: 'Impostazioni', view: 'settings' },
        { label: 'Servizi', view: 'services' },
      ],
    },
    {
      id: 'chat', title: 'Chat e agente',
      lead: 'Una conversazione con un modello sul progetto selezionato. Gli interruttori sopra il campo di testo controllano cosa può fare.',
      table: [
        ['Tools', 'l’agente legge, cerca, crea e modifica file, crea attività e controlla le pagine'],
        ['Web', 'ricerca sul web e lettura di pagine tramite URL (`web_search`, `fetch_url`)'],
        ['Modello', 'locale o cloud (☁); la scelta viene ricordata'],
      ],
      items: [
        '**Mappa del progetto.** Il modello riceve sempre da solo un albero compatto del progetto (più corto per i piccoli modelli locali, così non occupa la loro finestra): non c’è nulla da attivare. Il contenuto dei file lo legge con gli strumenti quando serve.',
        '**Invio** invia, **Maiusc+Invio** va a capo. Allega file e immagini con la graffetta o trascinandoli.',
        '**Screenshot → modello:** un modello di visione descrive l’immagine, poi il modello con strumenti costruisce il mockup come file. L’HTML o il codice inviato come esempio viene usato come base.',
        'Mentre lavora, la scheda «Chat» pulsa, sotto l’intestazione scorre una linea e il titolo della finestra mostra ●. La catena di passi («Leggo…», «Scrivo…») è ridotta a una riga: cliccala per vedere tutti i passi.',
        'In caso di errore sotto il messaggio compare il pulsante **«Riprova»**; anche il tuo messaggio ne ha uno (al passaggio del mouse).',
        '**Come procede il lavoro.** Mentre l’agente è occupato, in fondo alla chat c’è una riga viva con il segno otto animato: cosa sta facendo ora, da quanto tempo lavora e quanti token sono stati generati. Il ragionamento del modello (se ne produce) sta in un blocco comprimibile «Ragionamento». La risposta termina con una scheda «Modifiche»: quali file sono stati creati, modificati o eliminati e quante righe aggiunte o rimosse; i file HTML hanno un pulsante per aprirli nell’anteprima.',
      ],
    },
    {
      id: 'tools', title: 'Cosa sa fare l’agente',
      lead: 'Strumenti che il modello richiama da solo. Le operazioni sui file sono limitate alla cartella del progetto.',
      table: [
        ['run_command', 'esegue un comando nella cartella del progetto: avviare servizi (`docker compose`), creare un database, installare pacchetti, avviare il progetto; i processi lunghi vanno in background'],
        ['read_skill_file', 'legge un riferimento o un modello fornito con uno skill'],
        ['list_files / search_files', 'struttura del progetto e ricerca nei contenuti con classifica'],
        ['read_file', 'legge un file; i file grandi arrivano a pezzi: si prosegue con `start_line`/`end_line`'],
        ['write_file / append_file', 'crea e modifica file; quelli grandi vengono scritti a parti'],
        ['delete_file', 'elimina un file o una cartella (la radice del progetto è protetta)'],
        ['create_task / plan_task', 'crea un’attività o un piano a fasi nel pannello di destra'],
        ['web_search / fetch_url', 'cerca e legge siti; il contenuto delle pagine sono dati, non comandi'],
        ['preview_page', 'apre l’HTML in un vero browser: errori JS, scorrimento orizzontale a 375 px, ancore e immagini rotte, screenshot'],
        ['run_in_page', 'esegue uno scenario nella pagina (modulo, menu, pulsanti) e restituisce ciò che è successo davvero'],
        ['use_skill', 'carica una competenza: un insieme di regole esperte'],
      ],
      items: [
        '**I comandi richiedono la tua conferma** per impostazione predefinita: in chat compare una scheda con il comando e i pulsanti **Esegui / Rifiuta**. Impostazioni → Agente → «Comandi del terminale»: Chiedi / Auto / Off. I comandi che possono danneggiare il sistema non vengono mai eseguiti.',
        '**Verifica del risultato.** Dopo aver modificato una pagina l’agente deve aprirla ed eseguire gli scenari; «verificato» è ammesso solo se lo strumento lo conferma. Serve Microsoft Edge o Chrome: altrimenti l’agente dice onestamente che non ha potuto controllare.',
        'Non può uscire dal progetto, svuotare un file con `content` vuoto né scrivere in un file un segnaposto interno.',
      ],
    },
    {
      id: 'skills', title: 'Competenze (skills)',
      lead: 'Una competenza è una cartella con un `SKILL.md`: regole per un tipo di lavoro (design, verifica UI…). Quella adatta viene caricata dalle parole chiave della richiesta o con la chiamata `use_skill`.',
      items: [
        '**Integrati:** gli skill di Otto (web-design, verify-ui, ux-design, accessibility, ux-copy, responsive-mobile, code-review, testing, security-review, git-commits) e 14 skill ufficiali di Anthropic (frontend-design, canvas-design, theme-factory, mcp-builder, claude-api, webapp-testing, skill-creator, …; Apache 2.0, con l’etichetta «Anthropic»).',
        'In una richiesta entrano fino a due skill adatti; gli altri l’agente li carica con `use_skill` e ne legge i file con `read_skill_file`. A parità vince lo skill del progetto, poi il tuo, poi quello di Otto, poi quello ufficiale.',
        '**Pulsante Skill** accanto a Tools / Web: ricerca, gruppi per tipo e caselle. Il set viene salvato **per progetto e modello**; «Torna al set comune» lo reimposta.',
        '**I tuoi:** un `SKILL.md` in `<progetto>/.otto/skills/<nome>/` o nella cartella `skills` accanto al database dell’app. Intestazione: `name`, `description`, facoltativi `triggers` e `category`.',
        '**Libreria:** circa 300 skill ufficiali in più di Anthropic (plugin di Claude, knowledge-work: vendite, finanza, marketing, legale, dati, ingegneria…) e OpenAI (playwright, deploy su Vercel/Netlify/Cloudflare, sicurezza, Jupyter, voce…), tutti Apache 2.0 / MIT. Restano spenti finché non li selezioni nel pulsante Skill. Gli skill Figma e Claude Security non sono inclusi (licenze chiuse).',
      ],
      links: [{ label: 'Impostazioni', view: 'settings' }],
    },
    {
      id: 'tasks', title: 'Attività a fasi',
      items: [
        'Il pannello a destra: un’attività con una checklist. **«Pianifica con l’IA»** la divide in fasi; puoi aggiungere fasi a mano. Un piccolo modello locale che non chiama `plan_task` funziona comunque: un elenco numerato nella risposta diventa fasi.',
        '**▶ «Esegui per fasi»:** ogni fase parte da sola con contesto nuovo e si spunta da sé. Le fasi contrassegnate con **∥** (indipendenti, altri file) vanno in parallelo: quante insieme si imposta nelle Impostazioni (1–4).',
        '**Cosa sta succedendo.** Mentre un’attività gira, una barra sopra l’input mostra la fase e cosa fa l’agente ora, con **Pausa / Riprendi**, **Stop** e **Avanzamento** (il registro completo è nella scheda Agenti, dove ogni fase compare come «fase di attività»).',
        '**I guasti sono gestiti.** Limite di richieste di un modello gratuito → la fase aspetta un minuto e si ripete (fino a 5 volte). Chiamata di strumento corrotta di un modello locale → ripetuta fino a 3 volte. Il modello incolla codice nella risposta invece di scrivere il file → gli si chiede di nuovo e la fase non viene mai spuntata; se non scrive, l’attività si ferma con un errore.',
        'Dopo un errore o il riavvio dell’app l’attività mostra **Riprova** / **Continua**; una fase spuntata senza modifiche ai file ha un proprio **Riprova**. L’elenco «Fatto» è chiuso: clicca sull’intestazione.',
        'Per lavori grandi l’agente può pianificare da solo con `plan_task`. La scheda Agenti esegue lo stesso tipo di lavoro in background, senza chat aperta.',
        'Quando il progetto ha attività non finite, la scheda Chat mostra il loro numero e il bagliore del marchio (pulsa mentre una è in corso). Il pannello delle attività parte sempre chiuso.',
      ],
      links: [{ label: 'Agenti', view: 'agents' }],
    },
    {
      id: 'context', title: 'Contesto e metriche',
      lead: 'Un modello ricorda solo ciò che entra nella sua «finestra». La riga sotto la chat mostra `usato / finestra` e la velocità (token al secondo); cliccala per i dettagli.',
      items: [
        '**Colore:** verde fino al 70%, giallo fino al 90%, rosso oltre. Un `~` davanti al numero indica una stima (i provider cloud non sempre riportano i token esatti).',
        '**Risparmio di spazio:** i file grandi si leggono a pezzi; quando la finestra è piena oltre il 60%, i vecchi risultati degli strumenti vengono sostituiti da brevi note. Il compito e gli ultimi passi restano intatti.',
        '**Dimensione della finestra:** 32k token per i modelli locali (dimezzata automaticamente se il modello si blocca), 64k presunti per quelli cloud.',
        '**Poca VRAM?** Avvia Ollama con `OLLAMA_FLASH_ATTENTION=1` e `OLLAMA_KV_CACHE_TYPE=q8_0`: la cache occupa circa la metà.',
      ],
    },
    {
      id: 'cloud', title: 'Modelli cloud',
      lead: 'Piani gratuiti: serve solo una chiave API. La chiave resta su questo computer e viene verificata al salvataggio.',
      table: [
        ['OpenRouter', 'modelli contrassegnati `:free`, senza carta; il limite sono le richieste al giorno'],
        ['Groq', 'inferenza veloce con un limite gratuito di richieste/token'],
        ['Google Gemini', 'il piano gratuito di Google AI Studio'],
        ['Claude (Anthropic)', 'chiave API a pagamento da console.anthropic.com; protocollo nativo, livello di ragionamento'],
        ['Grok (xAI)', 'chiave a pagamento da console.x.ai (non è Groq)'],
        ['Cerebras', 'Llama/Qwen velocissimi con un limite gratuito proprio, separato da OpenRouter'],
        ['Mistral', 'modelli Codestral, Devstral e Mistral; piano gratuito per sperimentare'],
        ['OpenCode Zen', 'modelli gratuiti, la chiave la rilascia il servizio'],
        ['Server proprio', 'qualsiasi indirizzo compatibile con OpenAI (LM Studio, llama.cpp…): la chiave è facoltativa'],
      ],
      items: [
        '**I limiti sono per provider.** Tutti i modelli gratuiti di OpenRouter condividono un solo limite, quindi con un 429 l’agente passa a un modello di UN ALTRO provider (Groq, Gemini, Cerebras…) se hai la sua chiave; una fase di attività aspetta e ripete.',
        '**Cambio automatico.** Se un modello risponde con un errore (non disponibile, limite, richiesta non valida) o tace per 2 minuti, l’agente riprova prima con una richiesta più piccola, poi passa a un altro modello gratuito (fino a 3 volte) e lo scrive nella chat. Il selettore dei modelli segue il cambio.',
        'Un errore di chiave (401/403) non cambia modello: correggi la chiave nelle Impostazioni.',
        'I limiti del provider sono mostrati accanto alla chiave nelle Impostazioni.',
      ],
      links: [{ label: 'Impostazioni → Modelli cloud', view: 'settings' }],
    },
    {
      id: 'subscriptions', title: 'Claude e Codex con abbonamento',
      lead: 'Al posto di una chiave API, il tuo piano Claude Pro/Max o ChatGPT: Otto esegue il CLI ufficiale installato su questo computer con il tuo accesso.',
      items: [
        '**Attivazione:** Impostazioni → Modelli → «Claude con abbonamento (CLI)» e/o «Codex con abbonamento (CLI)». L’interruttore si salva subito; se il CLI non ha effettuato l’accesso, l’accesso si apre subito nel browser (anche l’errore in chat ha il pulsante **Accedi**).',
        '**Serve:** Claude Code (claude.ai/code) oppure l’app Codex / `npm i -g @openai/codex`. Otto non vede la password: l’accesso avviene sulla pagina del provider.',
        '**Versioni precise:** oltre a «sonnet / opus / haiku» (l’ultima di ogni linea) puoi scegliere una versione precisa: Opus 5.5, Sonnet 5.5, Fable 5.1, Haiku 4.5 e altre dall’elenco della tua chiave Claude API. Se il piano non include il modello, risponde Sonnet.',
        '**Modelli:** «Claude (abbonamento)» — Sonnet, Opus, Haiku; «Codex (abbonamento)» — solo i modelli del tuo piano (controllati una volta al giorno). Un modello senza accesso passa da solo a quello predefinito.',
        '**Limiti:** piano, quota usata e ora del reset sono nelle Impostazioni e accanto all’input; dopo ogni risposta il contatore del contesto mostra versione del modello, finestra, token e velocità.',
        '**Regole:** le modifiche ai file seguono Tools. Claude esegue comandi solo in modalità «Auto»; Codex nella sua sandbox (solo nella cartella del progetto).',
        'Per uso personale: non condividere il tuo accesso.',
      ],
    },
    {
      id: 'projects', title: 'Nuovi progetti',
      lead: 'Dove vengono creati i progetti e quali file iniziali aggiungere.',
      items: [
        '**Cartella dei progetti.** «Impostazioni → Cartella dei progetti»: qui finiscono i nuovi progetti creati senza una cartella collegata. I progetti esistenti restano dove sono.',
        '**File iniziali.** La finestra «Nuovo progetto» può aggiungere un `.gitignore` (Node.js, Python, Laravel, PHP, Java, Go, Rust, .NET, Flutter, Ruby o solo file di IDE e sistema), una licenza (MIT, Apache 2.0, GPL v3, AGPL v3, MPL 2.0, BSD, ISC, Unlicense) ed eseguire `git init`. I file esistenti non vengono mai sovrascritti. I testi di Apache, GPL, AGPL e MPL sono scaricati dall’elenco ufficiale SPDX, serve internet; offline `LICENSE` contiene un link.',
      ],
    },
    {
      id: 'files', title: 'File: editor e albero',
      items: [
        'L’albero nasconde le cartelle di servizio in base al tipo di progetto (`node_modules`, `vendor`, `target`, `dist`…). File e schede si trascinano.',
        'Evidenziazione della sintassi: JS/TS, JSON, CSS, HTML, Python, YAML, INI, Markdown, shell, SQL, PHP, NSIS.',
        '**Ctrl+F** fuori dall’editor è la ricerca globale nel progetto, dentro cerca nel file; **Ctrl+Maiusc+F** è sempre globale. Le corrispondenze sono evidenziate nei risultati e nel file.',
        'Sostituzione: **Ctrl+H** / **Ctrl+R** nel file, **Ctrl+Alt+R** in tutto il progetto. **Ctrl+S** salva, «Sync» rilegge l’albero dal disco.',
        '**Route:** la scheda «Route» elenca i percorsi (Laravel, FastAPI, Express, Next.js); un clic apre il controller alla riga giusta.',
        'Il pulsante «Codice» attiva la modalità focus (Esc per uscire). Il terminale integrato è in fondo alla finestra.',
        '**Esplora file:** rinomina (F2), elimina (nel cestino), duplica, trascina file e cartelle da Esplora risorse di Windows nell’albero; un nome già esistente viene rifiutato. Il pulsante `.env` crea il file da `.env.example` — o chiede all’IA di scriverlo.',
        '**Indice e completamento:** il progetto viene indicizzato (simboli e parole); l’apertura rapida cerca i file in modo approssimato e il completamento propone i nomi del progetto, inclusi i membri dopo `.`, `->` e `::`.',
      ],
      links: [{ label: 'File', view: 'project' }],
    },
    {
      id: 'preview', title: 'Anteprima dell’app',
      lead: 'La scheda «Anteprima» avvia il progetto e lo mostra direttamente in otto, dentro una cornice di telefono, tablet o computer.',
      items: [
        '**Avvio.** «Avvia» esegue il comando del progetto (`npm run dev`, `php artisan serve`, `manage.py runserver`: rilevato dai file, puoi modificarlo). L’indirizzo del dev server viene letto dal suo output e aperto nella cornice. Per un semplice sito HTML c’è il pulsante «Apri il sito»: non serve alcun processo.',
        '**Dispositivi.** iPhone, Pixel, Galaxy, iPad, portatile, Full HD oppure «Dimensione libera» con larghezza e altezza a scelta. Il pulsante di rotazione alterna verticale e orizzontale; lo zoom è «Adatta» o 50–125%. La pagina vede la vera larghezza dello schermo del dispositivo, quindi gli stili responsive si comportano come su un telefono.',
        '**Schermo intero.** Il pulsante con le frecce espande l’anteprima su tutta la finestra (Esc per uscire). Il pulsante ↗ apre l’indirizzo in un browser normale, quello del terminale mostra il log del server in esecuzione.',
        'Il server e i suoi processi si fermano insieme all’app. Se la pagina nella cornice resta vuota, il sito potrebbe vietare l’incorporamento: aprilo nel browser.',
        '**Che tipo di progetto.** L’anteprima riconosce lo stack dai file (Next.js, Vite, Laravel, Django, FastAPI, Docker Compose, Dev Container, …), mostra se c’è un’interfaccia e propone come avviarlo, ad esempio solo il front end di un monorepo oppure `docker compose up`.',
        '**Markup e componenti.** Qualsiasi file HTML/SVG del progetto si apre dall’elenco «File», senza server. Il pulsante «Anteprima» nell’editor e nella catena di passi dell’agente apre il file scritto dall’IA o da una persona. Quando il file cambia su disco la pagina si ricarica da sola. I componenti React/Vue/Svelte si vedono tramite il dev server: scrivi l’indirizzo della pagina nella barra degli indirizzi.',
      ],
    },
    {
      id: 'services', title: 'Servizi, strumenti e linguaggi',
      items: [
        '**Servizi:** più istanze di qualsiasi servizio (database, broker, client web) con porte automatiche; avvio uno alla volta con log in tempo reale (docker compose), stop, riavvio, copia delle credenziali.',
        '**Strumenti:** stato e installazione di Docker, Ollama, Git, GitHub CLI e linguaggi tramite winget.',
        '**Linguaggi:** runtime nel dev container; per PHP, estensioni e pacchetti Laravel.',
        '**Più versioni di PHP:** installa, reinstalla o rimuovi versioni; ogni progetto sceglie la sua e può avere un proprio `php.ini`. Composer segue da solo il PHP del progetto.',
        '**.env segue i servizi:** quando aggiungi un servizio o cambia la porta, il `.env` del progetto si aggiorna.',
      ],
      links: [{ label: 'Servizi', view: 'services' }],
    },
    {
      id: 'data', title: 'Database (scheda Dati)',
      lead: 'Un’area di lavoro in stile DataGrip per PostgreSQL, MySQL e MariaDB: tutto ciò che usa il progetto viene trovato e collegato da solo, senza digitare password.',
      items: [
        '**Connessioni automatiche:** dalla scheda Servizi e dal `.env` del progetto (`DATABASE_URL`, `DB_*`, `POSTGRES_*`, `MYSQL_*`; i nomi dei container diventano `localhost`). Aggiungi le tue con **+**; la password resta su questo computer. Sono ammessi solo indirizzi locali.',
        '**Albero a sinistra:** database → tabelle e viste con filtro. Un clic su una tabella la apre, un doppio clic su un database apre una console SQL.',
        '**Scheda tabella:** dati, struttura (colonne, chiavi, indici, chiavi esterne — un clic porta alla tabella collegata) e DDL. Doppio clic su una cella per modificarla (Invio salva, Esc annulla, il pulsante NULL imposta NULL); aggiungi o elimina righe; ordina dall’intestazione; filtra con un’espressione `WHERE`; pagine da 100; esporta CSV e JSON. Le righe si trovano con la chiave primaria: senza, la tabella è di sola lettura.',
        '**Console SQL:** evidenziazione, completamento di tabelle e colonne del database collegato, **Ctrl+Invio** esegue l’istruzione sotto il cursore (o la selezione), **EXPLAIN** (mai ANALYZE), cronologia delle query, esportazione del risultato.',
      ],
    },
    {
      id: 'ssh', title: 'SSH / SFTP',
      lead: 'Un client nello spirito di Bitvise: server, chiavi, file manager e comandi.',
      items: [
        '**Server:** elenco a sinistra (nome, host, porta, utente, cartella iniziale). Accesso con chiave o password; **«Ricorda la password»** la salva cifrata con l’archivio di sistema (non torna mai sullo schermo).',
        '**Chiavi:** genera Ed25519 / RSA / ECDSA con o senza passphrase, importa la tua, copia la chiave pubblica (aggiungila a `~/.ssh/authorized_keys` sul server). Le chiavi private restano su questo computer.',
        '**Fiducia:** alla prima connessione viene mostrata l’impronta del server e chiesta conferma. Se la chiave di un server noto cambia, ricevi un avviso e nessuna connessione silenziosa.',
        '**File:** questo computer a sinistra, il server a destra; scrivi un percorso a mano (Invio), seleziona con Ctrl, sposta con **→ / ←** o trascinando tra i pannelli o da Esplora risorse. Rinomina, chmod, elimina, nuova cartella; il doppio clic apre un file di testo per modificarlo (Ctrl+S).',
        '**Registro trasferimenti** sotto i pannelli: ogni caricamento, download e operazione con ora, durata e testo esatto dell’errore; puoi copiarlo o svuotarlo.',
        '**Comandi:** ogni comando gira sul server, la cartella corrente viene mantenuta, cronologia ↑/↓, completamento con Tab. I programmi interattivi (vim, top) non sono supportati.',
      ],
    },
    {
      id: 'plugins', title: 'Plugin',
      lead: 'Strumenti extra integrati in Otto; si attivano dalla barra laterale → Plugin, un plugin attivo ha un’icona in alto a destra.',
      items: [
        '**zeithub.coverty** — una cassaforte cifrata per password, login e link (AES-GCM 256 + PBKDF2) con generatore di password ed esportazione/importazione JSON. La password principale non si recupera; si blocca dopo 15 minuti di inattività.',
        '**zeithub.alertas** — calendario di promemoria e timer con notifiche e suono; il conto alla rovescia è sull’icona del plugin. Funziona finché Otto è aperto.',
        'Entrambi hanno l’aspetto delle estensioni originali e tengono i dati nella cartella dati dell’app.',
      ],
    },
    {
      id: 'models', title: 'Modelli',
      items: [
        'Un catalogo di modelli locali gratuiti (Ollama) per compito: chat, codice, ragionamento, visione. Download con avanzamento ed eliminazione; i modelli locali funzionano offline.',
        'Per gli screenshot serve un modello di visione (`qwen2.5vl`); per l’agente, un modello che supporti gli strumenti.',
      ],
      links: [{ label: 'Modelli', view: 'models' }],
    },
    {
      id: 'git', title: 'Git e account',
      items: [
        'Multi-account (in alto a destra): ogni account ha i propri progetti e le proprie chat.',
        'Aggiungi un account con un token, clona repository, cambia e crea rami.',
      ],
    },
    {
      id: 'look', title: 'Aspetto e lingue',
      items: [
        'Impostazioni → 13 schemi di colori (tra cui Dracula, Nord, Tokyo Night, One Dark, Gruvbox, Catppuccin, Solarized). Il testo sui pulsanti d’accento è scelto in base al contrasto.',
        'L’interfaccia e questa documentazione sono in 6 lingue: Русский, English, Azərbaycan, ქართული, Italiano, Español.',
      ],
      links: [{ label: 'Impostazioni', view: 'settings' }],
    },
    {
      id: 'keys', title: 'Scorciatoie da tastiera',
      table: [
        ['Invio / Maiusc+Invio', 'invia il messaggio / a capo'],
        ['Ctrl+F', 'cerca (nell’editor: nel file, fuori: nel progetto)'],
        ['Ctrl+Maiusc+F', 'ricerca globale'],
        ['Ctrl+H / Ctrl+R', 'sostituisci nel file'],
        ['Ctrl+Alt+R', 'sostituzione globale'],
        ['Ctrl+S', 'salva il file'],
        ['Ctrl+K', 'ricerca rapida'],
        ['Ctrl+Maiusc+O', 'simboli del file'],
        ['Ctrl+C / X / V / A / Z', 'copia, taglia, incolla, seleziona tutto, annulla ovunque (anche nei campi e nell’esplora file)'],
        ['↑ / ↓ nel terminale', 'cronologia dei comandi (per progetto, il testo non finito viene ripristinato)'],
        ['Tab nella console SSH', 'completa nomi di file e comandi sul server'],
        ['F2 / Canc nell’esplora file', 'rinomina / elimina (nel cestino)'],
        ['Esc', 'chiudi una finestra / esci dalla modalità focus'],
      ],
    },
    {
      id: 'privacy', title: 'Dati e sicurezza',
      items: [
        'Le chiavi SSH e le password salvate restano solo su questo computer (le password sono cifrate con l’archivio di sistema).',
        'Progetti, chat, attività e chiavi sono salvati in locale, nella cartella dati dell’app. I modelli locali non inviano nulla in rete.',
        'I modelli cloud ricevono solo ciò che è nella richiesta: il tuo messaggio, la cronologia della chat e il contenuto dei file letti dall’agente.',
        'L’agente resta dentro la cartella del progetto. Il server dell’app ascolta solo su `127.0.0.1`.',
      ],
    },
    {
      id: 'faq', title: 'Quando qualcosa non funziona',
      faq: [
        ['Claude / Codex con abbonamento: «accesso non eseguito»', 'Premi **Accedi** nel messaggio o in Impostazioni → Modelli: il CLI apre la pagina di accesso del provider nel browser. Poi ripeti la richiesta.'],
        ['Codex: «il modello non esiste o non hai accesso»', 'Quel modello non è nel tuo piano. Otto lo toglie dall’elenco e risponde con il modello predefinito.'],
        ['Una fase è spuntata ma nessun file è cambiato', 'Il modello ha incollato il codice nella risposta invece di chiamare `write_file` («file NON modificati» nella risposta). Ora queste fasi si ripetono e non vengono spuntate; per quelle vecchie usa **Riprova** sulla fase. I piccoli modelli locali lo fanno spesso: per modificare file usa un modello più grande o cloud.'],
        ['SSH: «Authentication failed»', 'Password errata, oppure la chiave pubblica non è in `~/.ssh/authorized_keys` di quell’utente. Copia la chiave pubblica dalla pagina Chiavi SSH.'],
        ['L’agente risponde con testo e non modifica i file', 'Controlla che l’interruttore **Tools** sia attivo e che il modello supporti gli strumenti (su OpenRouter solo i modelli contrassegnati tools). Sostituisci i modelli deboli: `qwen3-coder`, `qwen2.5-coder`.'],
        ['«Ollama non disponibile» / nessun modello locale', 'Verifica che Ollama sia in esecuzione (`ollama serve`) su `http://localhost:11434`; aggiorna l’elenco con il pulsante nel menu dei modelli.'],
        ['Un modello locale è andato in crash («terminated», «exit status»)', 'Di solito manca memoria: la finestra di contesto viene dimezzata automaticamente e la richiesta ripetuta. Se succede spesso, usa un modello più piccolo o abilita `OLLAMA_KV_CACHE_TYPE=q8_0`.'],
        ['Un modello cloud tace o restituisce 429', 'I modelli gratuiti hanno code e limiti giornalieri. Attendi (l’ora di reset è nell’errore) oppure l’agente passa da solo a un altro modello. I limiti sono visibili nelle Impostazioni.'],
        ['«invalid request» da un modello cloud', 'Alcuni modelli sono più severi sul formato della richiesta. L’agente ripete con una richiesta più piccola e passa a un altro modello; «Riprova» ricomincia.'],
        ['«Impossibile controllare la pagina»', '`preview_page` richiede Microsoft Edge o Google Chrome. Senza browser l’agente dice che il controllo è impossibile.'],
        ['L’installer .exe non si avvia', 'Windows Smart App Control blocca i programmi non firmati. Crea l’installer con GitHub Actions o firmalo con un certificato; durante lo sviluppo avvia l’app con `npm start`.'],
        ['La ricerca non guarda in node_modules', 'Le cartelle di servizio sono nascoste di proposito in base al tipo di progetto; apri quei file a mano se ti servono.'],
      ],
    },
  ],
};

export default text;
