import type { HelpText } from './types';

const text: HelpText = {
  title: 'Documentación',
  subtitle: 'zeithub.otto es un estudio de desarrollo local con IA: chat, agente con herramientas, editor, tareas, servicios y modelos en una sola ventana.',
  searchPlaceholder: 'Buscar en la documentación…',
  contents: 'Contenido',
  nothing: 'No se encontró nada. Prueba con otra palabra.',
  inMain: 'Se abre en la ventana principal',
  overview: 'Resumen',
  prev: 'Anterior',
  next: 'Siguiente',
  openWindow: 'Abrir en una ventana aparte',
  quick: [
    { n: '1', title: 'Conecta un modelo', text: 'Ollama local (pestaña «Modelos») o una clave de nube gratuita en Ajustes.', view: 'models' },
    { n: '2', title: 'Abre un proyecto', text: '«Nuevo proyecto» → elige una carpeta. El proyecto se expande al hacer clic; los chats están dentro.', view: 'chat' },
    { n: '3', title: 'Dale una tarea', text: 'Escribe en el chat qué hacer. El agente lee archivos, escribe código y comprueba la página en un navegador.', view: 'chat' },
  ],
  sections: [
    {
      id: 'start', title: 'Inicio rápido',
      lead: 'Tres pasos desde la instalación hasta el primer resultado.',
      items: [
        '**Modelo.** En local: pestaña «Modelos» → descarga un modelo de Ollama (para código sirven `qwen2.5-coder` o `qwen3-coder`). En la nube: Ajustes → Modelos en la nube → pega una clave gratuita de OpenRouter, Groq o Gemini.',
        '**Proyecto.** «Nuevo proyecto» → una carpeta con código. Los chats se crean con «Nuevo chat»; hacer clic en un proyecto solo lo expande.',
        '**Petición.** Describe la tarea con tus palabras: «añade un formulario de suscripción y comprueba que funciona». Activa **Tools**: sin él, el modelo solo responde con texto y no cambia archivos.',
        'En el primer arranque el asistente de configuración pregunta idioma, esquema y paquetes; todo se puede cambiar después.',
        '**Dónde está cada cosa:** Chat, Archivos, Datos y SSH en la barra superior; Agentes, Servicios, Modelos y Complementos arriba de la barra lateral izquierda; Vista previa, Modo código y la cuenta son los iconos de arriba a la derecha.',
      ],
      links: [
        { label: 'Modelos', view: 'models' },
        { label: 'Ajustes', view: 'settings' },
        { label: 'Servicios', view: 'services' },
      ],
    },
    {
      id: 'chat', title: 'Chat y agente',
      lead: 'Una conversación con un modelo sobre el proyecto seleccionado. Los interruptores sobre el campo de entrada controlan qué puede hacer.',
      table: [
        ['Tools', 'el agente lee, busca, crea y edita archivos, crea tareas y comprueba páginas'],
        ['Web', 'búsqueda en internet y lectura de páginas por URL (`web_search`, `fetch_url`)'],
        ['Modelo', 'local o en la nube (☁); la elección se recuerda'],
      ],
      items: [
        '**Mapa del proyecto.** El modelo siempre recibe por sí mismo un árbol compacto del proyecto (más corto para los modelos locales pequeños, para no ocupar su ventana): no hay nada que activar. El contenido de los archivos lo lee con herramientas cuando hace falta.',
        '**Enter** envía, **Shift+Enter** añade una línea. Adjunta archivos e imágenes con el clip o arrastrándolos.',
        '**Captura → plantilla:** un modelo de visión describe la imagen y luego el modelo con herramientas construye la maqueta como archivo. El HTML o código que envíes como muestra se usa como base.',
        'Mientras trabaja, la pestaña «Chat» pulsa, bajo la cabecera corre una línea y el título de la ventana muestra ●. La cadena de pasos («Leo…», «Escribo…») se reduce a una línea: haz clic para ver todos los pasos.',
        'Si hay un error, bajo el mensaje aparece el botón **«Reintentar»**; tu propio mensaje también lo tiene (al pasar el ratón).',
        '**Cómo se ve el trabajo.** Mientras el agente trabaja, al final del chat hay una línea viva con el signo otto animado: qué hace ahora, cuánto lleva y cuántos tokens se generaron. El razonamiento del modelo (si lo produce) va en un bloque plegable «Razonamiento». La respuesta termina con una tarjeta «Cambios»: qué archivos se crearon, modificaron o eliminaron y cuántas líneas se añadieron o quitaron; los archivos HTML tienen un botón para abrirlos en la vista previa.',
      ],
    },
    {
      id: 'tools', title: 'Qué sabe hacer el agente',
      lead: 'Herramientas que el modelo invoca por sí mismo. Las operaciones con archivos están limitadas a la carpeta del proyecto.',
      table: [
        ['run_command', 'ejecuta un comando en la carpeta del proyecto: levantar servicios (`docker compose`), crear una base, instalar paquetes, arrancar el proyecto; los procesos largos van en segundo plano'],
        ['read_skill_file', 'lee una referencia o plantilla que viene con un skill'],
        ['list_files / search_files', 'estructura del proyecto y búsqueda por contenido con ranking'],
        ['read_file', 'lee un archivo; los grandes llegan por partes: se continúa con `start_line`/`end_line`'],
        ['write_file / append_file', 'crea y modifica archivos; los grandes se escriben por partes'],
        ['delete_file', 'borra un archivo o carpeta (la raíz del proyecto está protegida)'],
        ['create_task / plan_task', 'crea una tarea o un plan por etapas en el panel derecho'],
        ['web_search / fetch_url', 'busca y lee sitios; el contenido de las páginas son datos, no órdenes'],
        ['preview_page', 'abre el HTML en un navegador real: errores de JS, desplazamiento horizontal a 375 px, anclas e imágenes rotas, captura'],
        ['run_in_page', 'ejecuta un escenario en la página (formulario, menú, botones) y devuelve lo que ocurrió de verdad'],
        ['use_skill', 'carga una habilidad: un conjunto de reglas expertas'],
      ],
      items: [
        '**Los comandos necesitan tu aprobación** por defecto: en el chat aparece una tarjeta con el comando y los botones **Ejecutar / Rechazar**. Ajustes → Agente → «Comandos de terminal»: Preguntar / Auto / Off. Los comandos que pueden dañar el sistema nunca se ejecutan.',
        '**Verificación del resultado.** Tras cambiar una página, el agente debe abrirla y ejecutar escenarios; «verificado» solo se permite si una herramienta lo confirmó. Hace falta Microsoft Edge o Chrome; si no, el agente dice honestamente que no pudo comprobarlo.',
        'No puede salir del proyecto, vaciar un archivo con `content` vacío ni escribir en un archivo un marcador interno.',
      ],
    },
    {
      id: 'skills', title: 'Habilidades (skills)',
      lead: 'Una habilidad es una carpeta con un `SKILL.md`: reglas para un tipo de trabajo (diseño, verificación de UI…). La adecuada se carga por palabras clave de tu petición o con la llamada `use_skill`.',
      items: [
        '**Incluidos:** los skills de Otto (web-design, verify-ui, ux-design, accessibility, ux-copy, responsive-mobile, code-review, testing, security-review, git-commits) y 14 skills oficiales de Anthropic (frontend-design, canvas-design, theme-factory, mcp-builder, claude-api, webapp-testing, skill-creator, …; Apache 2.0, con la marca «Anthropic»).',
        'En una petición entran hasta dos skills adecuados; los demás el agente los carga con `use_skill` y lee sus archivos con `read_skill_file`. En empate gana el del proyecto, luego el tuyo, luego el de Otto, luego el oficial.',
        '**Botón Skills** junto a Tools / Web: búsqueda, grupos por tipo y casillas. El conjunto se guarda **por proyecto y modelo**; «Volver al conjunto común» lo reinicia.',
        '**Los tuyos:** un `SKILL.md` en `<proyecto>/.otto/skills/<nombre>/` o en la carpeta `skills` junto a la base de datos de la app. Cabecera: `name`, `description`, opcionales `triggers` y `category`.',
        '**Biblioteca:** unos 300 skills oficiales más de Anthropic (plugins de Claude, knowledge-work: ventas, finanzas, marketing, legal, datos, ingeniería…) y OpenAI (playwright, despliegue en Vercel/Netlify/Cloudflare, seguridad, Jupyter, voz…), todos Apache 2.0 / MIT. Están apagados hasta que los marques en el botón Skills. No se incluyen los de Figma ni Claude Security (licencias cerradas).',
      ],
      links: [{ label: 'Ajustes', view: 'settings' }],
    },
    {
      id: 'tasks', title: 'Tareas por etapas',
      items: [
        'El panel derecho: una tarea con lista de comprobación. **«Planificar con IA»** la divide en etapas; también puedes añadir etapas a mano. Un modelo local pequeño que no llama a `plan_task` sigue funcionando: una lista numerada en su respuesta se convierte en etapas.',
        '**▶ «Ejecutar por etapas»:** cada etapa se ejecuta por separado con contexto nuevo y se marca sola. Las etapas marcadas con **∥** (independientes, otros archivos) se ejecutan en paralelo; cuántas a la vez se fija en Ajustes (1–4).',
        '**Qué está pasando.** Mientras corre una tarea, una barra sobre el campo de entrada muestra la etapa y lo que hace el agente ahora, con **Pausa / Reanudar**, **Detener** y **Progreso** (el registro completo está en la pestaña Agentes, donde cada etapa aparece como «etapa de tarea»).',
        '**Los fallos se gestionan.** Límite de peticiones de un modelo gratuito → la etapa espera un minuto y se repite (hasta 5 veces). Llamada a herramienta corrupta de un modelo local → se repite hasta 3 veces. Si el modelo pega código en la respuesta en vez de escribir el archivo → se le pide de nuevo y la etapa nunca se marca como hecha; si aun así no escribe, la tarea se detiene con un error.',
        'Tras un error o reiniciar la aplicación la tarea muestra **Reintentar** / **Continuar**; una etapa marcada sin cambios en archivos tiene su propio **Reintentar**. La lista «Hecho» está plegada: haz clic en su encabezado.',
        'Para trabajos grandes el agente puede planificar solo con `plan_task`. La pestaña Agentes ejecuta el mismo tipo de trabajo en segundo plano, sin un chat abierto.',
        'Cuando el proyecto tiene tareas sin terminar, la pestaña Chat muestra su número y el brillo de la marca (late mientras una se ejecuta). El panel de tareas siempre empieza plegado.',
      ],
      links: [{ label: 'Agentes', view: 'agents' }],
    },
    {
      id: 'context', title: 'Contexto y métricas',
      lead: 'Un modelo solo recuerda lo que cabe en su «ventana». La fila bajo el chat muestra `usado / ventana` y la velocidad (tokens por segundo); haz clic para ver los detalles.',
      items: [
        '**Color:** verde hasta el 70 %, amarillo hasta el 90 %, rojo por encima. Una `~` antes del número indica una estimación (los proveedores en la nube no siempre informan de los tokens exactos).',
        '**Ahorro de espacio:** los archivos grandes se leen por partes; cuando la ventana está llena más del 60 %, los resultados antiguos de herramientas se sustituyen por notas breves. La tarea y los últimos pasos no se tocan.',
        '**Tamaño de la ventana:** 32k tokens para modelos locales (se reduce a la mitad si el modelo falla), 64k supuestos para los de la nube.',
        '**¿Poca VRAM?** Inicia Ollama con `OLLAMA_FLASH_ATTENTION=1` y `OLLAMA_KV_CACHE_TYPE=q8_0`: la caché ocupa aproximadamente la mitad.',
      ],
    },
    {
      id: 'cloud', title: 'Modelos en la nube',
      lead: 'Planes gratuitos: solo hace falta una clave de API. La clave se guarda en este equipo y se verifica al guardarla.',
      table: [
        ['OpenRouter', 'modelos marcados `:free`, sin tarjeta; el límite son las peticiones por día'],
        ['Groq', 'inferencia rápida con un límite gratuito de peticiones/tokens'],
        ['Google Gemini', 'el plan gratuito de Google AI Studio'],
        ['Claude (Anthropic)', 'clave API de pago de console.anthropic.com; protocolo nativo, nivel de razonamiento'],
        ['Grok (xAI)', 'clave de pago de console.x.ai (no es Groq)'],
        ['Cerebras', 'Llama/Qwen muy rápidos con un límite gratuito propio, separado de OpenRouter'],
        ['Mistral', 'modelos Codestral, Devstral y Mistral; plan gratuito para experimentar'],
        ['OpenCode Zen', 'modelos gratuitos, la clave la emite el servicio'],
        ['Servidor propio', 'cualquier dirección compatible con OpenAI (LM Studio, llama.cpp…); la clave es opcional'],
      ],
      items: [
        '**Los límites son por proveedor.** Todos los modelos gratuitos de OpenRouter comparten un solo límite, así que ante un 429 el agente pasa a un modelo de OTRO proveedor (Groq, Gemini, Cerebras…) si tienes su clave; una etapa de tarea simplemente espera y se repite.',
        '**Cambio automático.** Si un modelo devuelve un error (no disponible, límite, petición inválida) o calla durante 2 minutos, el agente primero repite con una petición más pequeña y luego toma otro modelo gratuito (hasta 3 veces) y lo indica en el chat. El selector de modelos sigue el cambio.',
        'Un error de clave (401/403) no cambia de modelo: corrige la clave en Ajustes.',
        'Los límites del proveedor se muestran junto a la clave en Ajustes.',
      ],
      links: [{ label: 'Ajustes → Modelos en la nube', view: 'settings' }],
    },
    {
      id: 'subscriptions', title: 'Claude y Codex con suscripción',
      lead: 'En lugar de una clave API, tu plan Claude Pro/Max o ChatGPT: Otto ejecuta el CLI oficial instalado en este equipo con tu sesión.',
      items: [
        '**Activar:** Ajustes → Modelos → «Claude con suscripción (CLI)» y/o «Codex con suscripción (CLI)». El interruptor se guarda al momento; si el CLI no ha iniciado sesión, el inicio se abre en el navegador (el error del chat también tiene el botón **Iniciar sesión**).',
        '**Necesitas:** Claude Code (claude.ai/code) o la app Codex / `npm i -g @openai/codex`. Otto no ve tu contraseña: el inicio de sesión ocurre en la página del proveedor.',
        '**Versiones exactas:** además de «sonnet / opus / haiku» (la última de cada línea) puedes elegir una concreta: Opus 5.5, Sonnet 5.5, Fable 5.1, Haiku 4.5 y otras de la lista de tu clave de Claude API. Si el plan no incluye el modelo, responde Sonnet.',
        '**Modelos:** «Claude (suscripción)» — Sonnet, Opus, Haiku; «Codex (suscripción)» — solo los modelos de tu plan (se comprueba una vez al día). Un modelo sin acceso pasa solo al predeterminado.',
        '**Límites:** plan, parte usada y hora de reinicio en Ajustes y junto al campo de entrada; tras cada respuesta el contador de contexto muestra versión del modelo, ventana, tokens y velocidad.',
        '**Reglas:** la edición de archivos sigue al botón Tools. Claude ejecuta comandos solo en modo «Auto»; Codex dentro de su sandbox (solo en la carpeta del proyecto).',
        'Para uso personal: no compartas tu acceso.',
      ],
    },
    {
      id: 'projects', title: 'Proyectos nuevos',
      lead: 'Dónde se crean los proyectos y qué archivos iniciales añadir.',
      items: [
        '**Carpeta de proyectos.** «Ajustes → Carpeta de proyectos»: aquí se crean los proyectos nuevos sin carpeta asociada. Los proyectos existentes se quedan donde están.',
        '**Archivos iniciales.** La ventana «Nuevo proyecto» puede añadir un `.gitignore` (Node.js, Python, Laravel, PHP, Java, Go, Rust, .NET, Flutter, Ruby o solo archivos de IDE y sistema), una licencia (MIT, Apache 2.0, GPL v3, AGPL v3, MPL 2.0, BSD, ISC, Unlicense) y ejecutar `git init`. Los archivos existentes nunca se sobrescriben. Los textos de Apache, GPL, AGPL y MPL se descargan de la lista oficial de SPDX, hace falta internet; sin conexión `LICENSE` lleva un enlace.',
      ],
    },
    {
      id: 'files', title: 'Archivos: editor y árbol',
      items: [
        'El árbol oculta carpetas de servicio según el tipo de proyecto (`node_modules`, `vendor`, `target`, `dist`…). Archivos y pestañas se pueden arrastrar.',
        'Resaltado de sintaxis: JS/TS, JSON, CSS, HTML, Python, YAML, INI, Markdown, shell, SQL, PHP, NSIS.',
        '**Ctrl+F** fuera del editor es una búsqueda global en el proyecto, dentro busca en el archivo; **Ctrl+Shift+F** siempre es global. Las coincidencias se resaltan en los resultados y en el archivo.',
        'Reemplazo: **Ctrl+H** / **Ctrl+R** en el archivo, **Ctrl+Alt+R** en todo el proyecto. **Ctrl+S** guarda, «Sync» relee el árbol desde el disco.',
        '**Rutas:** la pestaña «Rutas» lista las rutas (Laravel, FastAPI, Express, Next.js); un clic abre el controlador en la línea correcta.',
        'El botón «Código» activa el modo de enfoque (Esc para salir). El terminal integrado está en la parte inferior de la ventana.',
        '**Explorador:** renombrar (F2), eliminar (a la papelera), duplicar, arrastrar archivos y carpetas desde el Explorador de Windows al árbol; un nombre que ya existe se rechaza. El botón `.env` crea el archivo desde `.env.example` — o pide a la IA que lo escriba.',
        '**Índice y autocompletado:** el proyecto se indexa (símbolos y palabras); la apertura rápida busca archivos de forma aproximada y el autocompletado ofrece los nombres del proyecto, incluidos los miembros tras `.`, `->` y `::`.',
      ],
      links: [{ label: 'Archivos', view: 'project' }],
    },
    {
      id: 'preview', title: 'Vista previa de la app',
      lead: 'La pestaña «Vista previa» ejecuta el proyecto y lo muestra dentro de otto, en un marco de teléfono, tableta u ordenador.',
      items: [
        '**Ejecución.** «Ejecutar» lanza el comando del proyecto (`npm run dev`, `php artisan serve`, `manage.py runserver`: se detecta por los archivos y puedes cambiarlo). La dirección del servidor de desarrollo se toma de su salida y se abre en el marco. Para un sitio HTML simple hay un botón «Abrir el sitio»: no hace falta ningún proceso.',
        '**Dispositivos.** iPhone, Pixel, Galaxy, iPad, portátil, Full HD o «Tamaño libre» con tu propio ancho y alto. El botón de giro alterna vertical y horizontal; el zoom es «Ajustar» o 50–125 %. La página ve el ancho real de pantalla del dispositivo, así que los estilos adaptables se comportan como en un teléfono.',
        '**Pantalla completa.** El botón de flechas expande la vista previa a toda la ventana (Esc para salir). El botón ↗ abre la dirección en un navegador normal y el del terminal muestra el registro del servidor en marcha.',
        'El servidor y sus procesos se detienen junto con la app. Si la página del marco queda en blanco, el sitio puede prohibir incrustarse: ábrelo en el navegador.',
        '**Qué tipo de proyecto.** La vista previa reconoce el stack por los archivos (Next.js, Vite, Laravel, Django, FastAPI, Docker Compose, Dev Container, …), muestra si hay interfaz y ofrece formas de iniciarlo, por ejemplo solo el front end de un monorepo o `docker compose up`.',
        '**Maquetación y componentes.** Cualquier archivo HTML/SVG del proyecto se abre desde la lista «Archivo», sin servidor. El botón «Vista previa» del editor y de la cadena de pasos del agente abre el archivo escrito por la IA o por una persona. Cuando el archivo cambia en disco la página se recarga sola. Los componentes React/Vue/Svelte se ven a través del servidor de desarrollo: escribe la dirección de la página en la barra de direcciones.',
      ],
    },
    {
      id: 'services', title: 'Servicios, herramientas y lenguajes',
      items: [
        '**Servicios:** varias instancias de cualquier servicio (bases de datos, brokers, clientes web) con puertos automáticos; inicio uno a uno con registro en vivo (docker compose), parada, reinicio, copia de credenciales.',
        '**Herramientas:** estado e instalación de Docker, Ollama, Git, GitHub CLI y lenguajes mediante winget.',
        '**Lenguajes:** entornos de ejecución en el dev container; para PHP, extensiones y paquetes de Laravel.',
        '**Varias versiones de PHP:** instala, reinstala o elimina versiones; cada proyecto elige la suya y puede tener su propio `php.ini`. Composer sigue solo el PHP del proyecto.',
        '**.env sigue a los servicios:** al añadir un servicio o cambiar su puerto, el `.env` del proyecto se actualiza.',
      ],
      links: [{ label: 'Servicios', view: 'services' }],
    },
    {
      id: 'data', title: 'Bases de datos (pestaña Datos)',
      lead: 'Un espacio de trabajo al estilo DataGrip para PostgreSQL, MySQL y MariaDB: todo lo que usa el proyecto se encuentra y se conecta solo, sin escribir contraseñas.',
      items: [
        '**Conexiones automáticas:** desde la pestaña Servicios y desde el `.env` del proyecto (`DATABASE_URL`, `DB_*`, `POSTGRES_*`, `MYSQL_*`; los nombres de contenedor pasan a `localhost`). Añade las tuyas con **+**; la contraseña queda solo en este equipo. Solo se permiten direcciones locales.',
        '**Árbol a la izquierda:** bases → tablas y vistas con filtro. Un clic en una tabla la abre, doble clic en una base abre una consola SQL.',
        '**Pestaña de tabla:** datos, estructura (columnas, claves, índices, claves foráneas — un clic lleva a la tabla referenciada) y DDL. Doble clic en una celda para editarla (Intro guarda, Esc cancela, el botón NULL pone NULL); añadir o eliminar filas; ordenar por el encabezado; filtrar con una expresión `WHERE`; páginas de 100; exportar CSV y JSON. Las filas se localizan por la clave primaria: sin ella la tabla es de solo lectura.',
        '**Consola SQL:** resaltado, autocompletado de tablas y columnas de la base conectada, **Ctrl+Intro** ejecuta la sentencia bajo el cursor (o la selección), **EXPLAIN** (nunca ANALYZE), historial de consultas, exportación del resultado.',
      ],
    },
    {
      id: 'ssh', title: 'SSH / SFTP',
      lead: 'Un cliente al estilo de Bitvise: servidores, claves, gestor de archivos y comandos.',
      items: [
        '**Servidores:** lista a la izquierda (nombre, host, puerto, usuario, carpeta inicial). Acceso con clave o contraseña; **«Recordar la contraseña»** la guarda cifrada con el almacén del sistema (nunca vuelve a la pantalla).',
        '**Claves:** genera Ed25519 / RSA / ECDSA con o sin frase de paso, importa la tuya, copia la clave pública (añádela a `~/.ssh/authorized_keys` en el servidor). Las claves privadas quedan en este equipo.',
        '**Confianza:** en la primera conexión se muestra la huella del servidor y se pide confirmación. Si la clave de un servidor conocido cambia, recibes una advertencia y no una conexión silenciosa.',
        '**Archivos:** este equipo a la izquierda, el servidor a la derecha; escribe una ruta a mano (Intro), selecciona con Ctrl, mueve con **→ / ←** o arrastrando entre paneles o desde el Explorador de Windows. Renombrar, chmod, eliminar, nueva carpeta; doble clic abre un archivo de texto para editarlo (Ctrl+S).',
        '**Registro de transferencias** bajo los paneles: cada subida, descarga y operación con hora, duración y el texto exacto del error; puedes copiarlo o limpiarlo.',
        '**Comandos:** cada comando se ejecuta en el servidor, se mantiene la carpeta actual, historial ↑/↓, autocompletado con Tab. Los programas interactivos (vim, top) no son compatibles.',
      ],
    },
    {
      id: 'plugins', title: 'Complementos',
      lead: 'Herramientas extra integradas en Otto; se activan en la barra lateral → Complementos y uno activo muestra un icono arriba a la derecha.',
      items: [
        '**zeithub.coverty** — bóveda cifrada para contraseñas, inicios de sesión y enlaces (AES-GCM 256 + PBKDF2) con generador de contraseñas y exportación/importación JSON. La contraseña maestra no se recupera; se bloquea tras 15 minutos sin uso.',
        '**zeithub.alertas** — calendario de recordatorios y temporizador con notificaciones y sonido; la cuenta atrás se ve en el icono. Funciona mientras Otto esté abierto.',
        'Ambos se ven como las extensiones originales y guardan sus datos en la carpeta de datos de la app.',
      ],
    },
    {
      id: 'models', title: 'Modelos',
      items: [
        'Un catálogo de modelos locales gratuitos (Ollama) por tarea: chat, código, razonamiento, visión. Descarga con progreso y borrado; los modelos locales funcionan sin conexión.',
        'Para las capturas hace falta un modelo de visión (`qwen2.5vl`); para el agente, un modelo con soporte de herramientas.',
      ],
      links: [{ label: 'Modelos', view: 'models' }],
    },
    {
      id: 'git', title: 'Git y cuentas',
      items: [
        'Multicuenta (arriba a la derecha): cada cuenta tiene sus propios proyectos y chats.',
        'Añade una cuenta con un token, clona repositorios, cambia y crea ramas.',
      ],
    },
    {
      id: 'look', title: 'Apariencia e idiomas',
      items: [
        'Ajustes → 13 esquemas de color (entre ellos Dracula, Nord, Tokyo Night, One Dark, Gruvbox, Catppuccin, Solarized). El texto de los botones de acento se elige por contraste.',
        'La interfaz y esta documentación están en 6 idiomas: Русский, English, Azərbaycan, ქართული, Italiano, Español.',
      ],
      links: [{ label: 'Ajustes', view: 'settings' }],
    },
    {
      id: 'keys', title: 'Atajos de teclado',
      table: [
        ['Enter / Shift+Enter', 'enviar el mensaje / nueva línea'],
        ['Ctrl+F', 'buscar (en el editor: en el archivo; fuera: en el proyecto)'],
        ['Ctrl+Shift+F', 'búsqueda global'],
        ['Ctrl+H / Ctrl+R', 'reemplazar en el archivo'],
        ['Ctrl+Alt+R', 'reemplazo global'],
        ['Ctrl+S', 'guardar el archivo'],
        ['Ctrl+K', 'búsqueda rápida'],
        ['Ctrl+Shift+O', 'símbolos del archivo'],
        ['Ctrl+C / X / V / A / Z', 'copiar, cortar, pegar, seleccionar todo, deshacer en todas partes (también en campos y en el explorador)'],
        ['↑ / ↓ en un terminal', 'historial de comandos (por proyecto, el texto sin terminar se restaura)'],
        ['Tab en la consola SSH', 'completa nombres de archivos y comandos en el servidor'],
        ['F2 / Supr en el explorador', 'renombrar / eliminar (a la papelera)'],
        ['Esc', 'cerrar un diálogo / salir del modo de enfoque'],
      ],
    },
    {
      id: 'privacy', title: 'Datos y seguridad',
      items: [
        'Las claves SSH y las contraseñas guardadas están solo en este equipo (las contraseñas se cifran con el almacén del sistema).',
        'Proyectos, chats, tareas y claves se guardan en local, en la carpeta de datos de la app. Los modelos locales no envían nada por la red.',
        'Los modelos en la nube reciben solo lo que va en la petición: tu mensaje, el historial del chat y el contenido de los archivos que el agente leyó.',
        'El agente permanece dentro de la carpeta del proyecto. El servidor de la app escucha solo en `127.0.0.1`.',
      ],
    },
    {
      id: 'faq', title: 'Cuando algo no funciona',
      faq: [
        ['Claude / Codex con suscripción: «no has iniciado sesión»', 'Pulsa **Iniciar sesión** en el mensaje o en Ajustes → Modelos: el CLI abre la página de inicio del proveedor en el navegador. Luego repite la petición.'],
        ['Codex: «el modelo no existe o no tienes acceso»', 'Ese modelo no está en tu plan. Otto lo quita de la lista y responde con el modelo predeterminado.'],
        ['Una etapa está marcada pero ningún archivo cambió', 'El modelo pegó el código en la respuesta en vez de llamar a `write_file` («archivos NO modificados» en la respuesta). Ahora esas etapas se repiten y no se marcan; para las antiguas usa **Reintentar** en la etapa. Los modelos locales pequeños lo hacen a menudo: para editar archivos usa uno más grande o en la nube.'],
        ['SSH: «Authentication failed»', 'Contraseña incorrecta, o la clave pública no está en `~/.ssh/authorized_keys` de ese usuario. Copia la clave pública desde la página de claves SSH.'],
        ['El agente responde con texto y no cambia archivos', 'Comprueba que el interruptor **Tools** esté activado y que el modelo admita herramientas (en OpenRouter solo los marcados tools). Sustituye los modelos débiles: `qwen3-coder`, `qwen2.5-coder`.'],
        ['«Ollama no disponible» / no hay modelos locales', 'Asegúrate de que Ollama esté en marcha (`ollama serve`) en `http://localhost:11434`; actualiza la lista con el botón del menú de modelos.'],
        ['Un modelo local se cayó («terminated», «exit status»)', 'Normalmente falta memoria: la ventana de contexto se reduce a la mitad automáticamente y se repite la petición. Si ocurre a menudo, usa un modelo más pequeño o activa `OLLAMA_KV_CACHE_TYPE=q8_0`.'],
        ['Un modelo en la nube calla o devuelve 429', 'Los modelos gratuitos tienen colas y límites diarios. Espera (la hora de reinicio está en el error) o el agente cambiará solo a otro modelo. Los límites se ven en Ajustes.'],
        ['«invalid request» de un modelo en la nube', 'Algunos modelos son más estrictos con el formato de la petición. El agente repite con una petición más pequeña y cambia a otro modelo; «Reintentar» empieza de nuevo.'],
        ['«No se pudo comprobar la página»', '`preview_page` necesita Microsoft Edge o Google Chrome. Sin navegador el agente dice que la comprobación es imposible.'],
        ['El instalador .exe no arranca', 'Windows Smart App Control bloquea programas sin firmar. Genera el instalador en GitHub Actions o fírmalo con un certificado; durante el desarrollo ejecuta la app con `npm start`.'],
        ['La búsqueda no mira en node_modules', 'Las carpetas de servicio se ocultan a propósito según el tipo de proyecto; abre esos archivos a mano si los necesitas.'],
      ],
    },
  ],
};

export default text;
